apiVersion: v1
kind: Service
metadata:
  name: {{ include "gaiaos.fullname" . }}-admin-ui
  labels:
    app.kubernetes.io/name: {{ include "gaiaos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admin-ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.adminUiPort }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "gaiaos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admin-ui
