"""Contract verification tests for CLI agent plugin scaffolding."""

from __future__ import annotations

import ast
import importlib.util
import inspect
import typing
from pathlib import Path

from gaiaos_cli.main import app
from typer.testing import CliRunner

from orchestrator.schemas.agent_io import AgentInput, AgentOutput

runner = CliRunner()


def test_cli_plugin_scaffold_contract_compatibility(tmp_path: Path) -> None:
    """Verify code generated by gaiaos plugin scaffold satisfies agent IO contract."""
    # Mirror scripts/new_agent_template into tmp_path
    template_src = Path.cwd() / "scripts" / "new_agent_template"
    template_dst = tmp_path / "scripts" / "new_agent_template"
    template_dst.mkdir(parents=True, exist_ok=True)
    for item in template_src.iterdir():
        if item.is_file():
            content = item.read_text(encoding="utf-8")
            template_dst.joinpath(item.name).write_text(content, encoding="utf-8")

    domain = "space_weather"
    result = runner.invoke(app, ["plugin", "scaffold", domain, "-d", str(tmp_path)])
    assert result.exit_code == 0
    assert f"Successfully scaffolded new domain agent '{domain}'" in result.stdout

    agent_file = tmp_path / "orchestrator" / "agents" / domain / "agent.py"
    test_file = tmp_path / "tests" / f"test_{domain}_agent.py"
    init_file = tmp_path / "orchestrator" / "agents" / domain / "__init__.py"

    assert agent_file.exists()
    assert test_file.exists()
    assert init_file.exists()

    # Verify AST syntax
    ast.parse(agent_file.read_text(encoding="utf-8"))
    ast.parse(test_file.read_text(encoding="utf-8"))
    ast.parse(init_file.read_text(encoding="utf-8"))

    # Dynamically import generated agent module and verify contract
    spec = importlib.util.spec_from_file_location(f"{domain}_agent", str(agent_file))
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    assert hasattr(mod, "run")
    assert inspect.iscoroutinefunction(mod.run)

    hints = typing.get_type_hints(mod.run)
    params = list(inspect.signature(mod.run).parameters.values())
    assert len(params) == 1
    assert hints.get(params[0].name) is AgentInput
    assert hints.get("return") is AgentOutput
