# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.alert_message_response import AlertMessageResponse
from ...models.http_validation_error import HTTPValidationError
from typing import cast
from uuid import UUID



def _get_kwargs(
    rule_id: UUID,

) -> dict[str, Any]:
    

    

    

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/api/v1/admin/alert-rules/{rule_id}".format(rule_id=quote(str(rule_id), safe=""),),
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> AlertMessageResponse | Any | HTTPValidationError | None:
    if response.status_code == 200:
        response_200 = AlertMessageResponse.from_dict(response.json())



        return response_200

    if response.status_code == 404:
        response_404 = cast(Any, None)
        return response_404

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[AlertMessageResponse | Any | HTTPValidationError]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    rule_id: UUID,
    *,
    client: AuthenticatedClient | Client,

) -> Response[AlertMessageResponse | Any | HTTPValidationError]:
    """ Delete an alert rule

     Delete an alert rule by primary key ID.

    Args:
        rule_id (UUID):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AlertMessageResponse | Any | HTTPValidationError]
     """


    kwargs = _get_kwargs(
        rule_id=rule_id,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    rule_id: UUID,
    *,
    client: AuthenticatedClient | Client,

) -> AlertMessageResponse | Any | HTTPValidationError | None:
    """ Delete an alert rule

     Delete an alert rule by primary key ID.

    Args:
        rule_id (UUID):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AlertMessageResponse | Any | HTTPValidationError
     """


    return sync_detailed(
        rule_id=rule_id,
client=client,

    ).parsed

async def asyncio_detailed(
    rule_id: UUID,
    *,
    client: AuthenticatedClient | Client,

) -> Response[AlertMessageResponse | Any | HTTPValidationError]:
    """ Delete an alert rule

     Delete an alert rule by primary key ID.

    Args:
        rule_id (UUID):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AlertMessageResponse | Any | HTTPValidationError]
     """


    kwargs = _get_kwargs(
        rule_id=rule_id,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    rule_id: UUID,
    *,
    client: AuthenticatedClient | Client,

) -> AlertMessageResponse | Any | HTTPValidationError | None:
    """ Delete an alert rule

     Delete an alert rule by primary key ID.

    Args:
        rule_id (UUID):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AlertMessageResponse | Any | HTTPValidationError
     """


    return (await asyncio_detailed(
        rule_id=rule_id,
client=client,

    )).parsed
