# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.error_response import ErrorResponse
from ...models.http_validation_error import HTTPValidationError
from ...models.investigation_status_response import InvestigationStatusResponse
from typing import cast
from uuid import UUID



def _get_kwargs(
    investigation_id: UUID,

) -> dict[str, Any]:
    

    

    

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/investigations/{investigation_id}".format(investigation_id=quote(str(investigation_id), safe=""),),
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> ErrorResponse | HTTPValidationError | InvestigationStatusResponse | None:
    if response.status_code == 200:
        response_200 = InvestigationStatusResponse.from_dict(response.json())



        return response_200

    if response.status_code == 403:
        response_403 = ErrorResponse.from_dict(response.json())



        return response_403

    if response.status_code == 404:
        response_404 = ErrorResponse.from_dict(response.json())



        return response_404

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ErrorResponse | HTTPValidationError | InvestigationStatusResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    investigation_id: UUID,
    *,
    client: AuthenticatedClient | Client,

) -> Response[ErrorResponse | HTTPValidationError | InvestigationStatusResponse]:
    """ Get Investigation

     Retrieve the status and results of an investigation.

    Args:
        investigation_id (UUID):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | HTTPValidationError | InvestigationStatusResponse]
     """


    kwargs = _get_kwargs(
        investigation_id=investigation_id,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    investigation_id: UUID,
    *,
    client: AuthenticatedClient | Client,

) -> ErrorResponse | HTTPValidationError | InvestigationStatusResponse | None:
    """ Get Investigation

     Retrieve the status and results of an investigation.

    Args:
        investigation_id (UUID):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | HTTPValidationError | InvestigationStatusResponse
     """


    return sync_detailed(
        investigation_id=investigation_id,
client=client,

    ).parsed

async def asyncio_detailed(
    investigation_id: UUID,
    *,
    client: AuthenticatedClient | Client,

) -> Response[ErrorResponse | HTTPValidationError | InvestigationStatusResponse]:
    """ Get Investigation

     Retrieve the status and results of an investigation.

    Args:
        investigation_id (UUID):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | HTTPValidationError | InvestigationStatusResponse]
     """


    kwargs = _get_kwargs(
        investigation_id=investigation_id,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    investigation_id: UUID,
    *,
    client: AuthenticatedClient | Client,

) -> ErrorResponse | HTTPValidationError | InvestigationStatusResponse | None:
    """ Get Investigation

     Retrieve the status and results of an investigation.

    Args:
        investigation_id (UUID):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | HTTPValidationError | InvestigationStatusResponse
     """


    return (await asyncio_detailed(
        investigation_id=investigation_id,
client=client,

    )).parsed
