# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.get_admin_metrics_api_v1_admin_metrics_get_window import GetAdminMetricsApiV1AdminMetricsGetWindow
from ...models.group_by import GroupBy
from ...models.http_validation_error import HTTPValidationError
from ...models.metrics_response import MetricsResponse
from ...types import UNSET, Unset
from typing import cast



def _get_kwargs(
    *,
    window: GetAdminMetricsApiV1AdminMetricsGetWindow | Unset = GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1,
    group_by: GroupBy | Unset = UNSET,
    event_type: None | str | Unset = UNSET,

) -> dict[str, Any]:
    

    

    params: dict[str, Any] = {}

    json_window: str | Unset = UNSET
    if not isinstance(window, Unset):
        json_window = window.value

    params["window"] = json_window

    json_group_by: str | Unset = UNSET
    if not isinstance(group_by, Unset):
        json_group_by = group_by.value

    params["group_by"] = json_group_by

    json_event_type: None | str | Unset
    if isinstance(event_type, Unset):
        json_event_type = UNSET
    else:
        json_event_type = event_type
    params["event_type"] = json_event_type


    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}


    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/admin/metrics",
        "params": params,
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> HTTPValidationError | MetricsResponse | None:
    if response.status_code == 200:
        response_200 = MetricsResponse.from_dict(response.json())



        return response_200

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[HTTPValidationError | MetricsResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    window: GetAdminMetricsApiV1AdminMetricsGetWindow | Unset = GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1,
    group_by: GroupBy | Unset = UNSET,
    event_type: None | str | Unset = UNSET,

) -> Response[HTTPValidationError | MetricsResponse]:
    """ Aggregated observability metrics

     Returns aggregated p50/p95 latency, success rate, cost estimate rollups, advisory worker scaling
    recommendations, and historical telemetry for the requested window. Supports optional event_type
    filtering. Requires ADMIN role.

    Args:
        window (GetAdminMetricsApiV1AdminMetricsGetWindow | Unset):  Default:
            GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1.
        group_by (GroupBy | Unset): Safe enumeration of supported group_by dimensions.

            Values map to fixed SQL expressions via GROUP_BY_SQL below; no user string
            is ever interpolated into a query.

            Notes
            -----
            ``COMPLEXITY_TIER`` groups investigation jobs by the tier assigned during
            graph execution ("trivial" | "moderate" | "complex"). Rows where
            ``group_key`` is NULL are investigations that did not complete tier
            classification (e.g. early failure before the supervisor ran).

            ``DAY`` groups all event types by calendar day (UTC).

            ``EVENT_TYPE`` groups rows by event_type ("JobCompleted" | "IngestionCompleted" | ...).
        event_type (None | str | Unset): Optional event_type filter

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[HTTPValidationError | MetricsResponse]
     """


    kwargs = _get_kwargs(
        window=window,
group_by=group_by,
event_type=event_type,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,
    window: GetAdminMetricsApiV1AdminMetricsGetWindow | Unset = GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1,
    group_by: GroupBy | Unset = UNSET,
    event_type: None | str | Unset = UNSET,

) -> HTTPValidationError | MetricsResponse | None:
    """ Aggregated observability metrics

     Returns aggregated p50/p95 latency, success rate, cost estimate rollups, advisory worker scaling
    recommendations, and historical telemetry for the requested window. Supports optional event_type
    filtering. Requires ADMIN role.

    Args:
        window (GetAdminMetricsApiV1AdminMetricsGetWindow | Unset):  Default:
            GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1.
        group_by (GroupBy | Unset): Safe enumeration of supported group_by dimensions.

            Values map to fixed SQL expressions via GROUP_BY_SQL below; no user string
            is ever interpolated into a query.

            Notes
            -----
            ``COMPLEXITY_TIER`` groups investigation jobs by the tier assigned during
            graph execution ("trivial" | "moderate" | "complex"). Rows where
            ``group_key`` is NULL are investigations that did not complete tier
            classification (e.g. early failure before the supervisor ran).

            ``DAY`` groups all event types by calendar day (UTC).

            ``EVENT_TYPE`` groups rows by event_type ("JobCompleted" | "IngestionCompleted" | ...).
        event_type (None | str | Unset): Optional event_type filter

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        HTTPValidationError | MetricsResponse
     """


    return sync_detailed(
        client=client,
window=window,
group_by=group_by,
event_type=event_type,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    window: GetAdminMetricsApiV1AdminMetricsGetWindow | Unset = GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1,
    group_by: GroupBy | Unset = UNSET,
    event_type: None | str | Unset = UNSET,

) -> Response[HTTPValidationError | MetricsResponse]:
    """ Aggregated observability metrics

     Returns aggregated p50/p95 latency, success rate, cost estimate rollups, advisory worker scaling
    recommendations, and historical telemetry for the requested window. Supports optional event_type
    filtering. Requires ADMIN role.

    Args:
        window (GetAdminMetricsApiV1AdminMetricsGetWindow | Unset):  Default:
            GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1.
        group_by (GroupBy | Unset): Safe enumeration of supported group_by dimensions.

            Values map to fixed SQL expressions via GROUP_BY_SQL below; no user string
            is ever interpolated into a query.

            Notes
            -----
            ``COMPLEXITY_TIER`` groups investigation jobs by the tier assigned during
            graph execution ("trivial" | "moderate" | "complex"). Rows where
            ``group_key`` is NULL are investigations that did not complete tier
            classification (e.g. early failure before the supervisor ran).

            ``DAY`` groups all event types by calendar day (UTC).

            ``EVENT_TYPE`` groups rows by event_type ("JobCompleted" | "IngestionCompleted" | ...).
        event_type (None | str | Unset): Optional event_type filter

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[HTTPValidationError | MetricsResponse]
     """


    kwargs = _get_kwargs(
        window=window,
group_by=group_by,
event_type=event_type,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    window: GetAdminMetricsApiV1AdminMetricsGetWindow | Unset = GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1,
    group_by: GroupBy | Unset = UNSET,
    event_type: None | str | Unset = UNSET,

) -> HTTPValidationError | MetricsResponse | None:
    """ Aggregated observability metrics

     Returns aggregated p50/p95 latency, success rate, cost estimate rollups, advisory worker scaling
    recommendations, and historical telemetry for the requested window. Supports optional event_type
    filtering. Requires ADMIN role.

    Args:
        window (GetAdminMetricsApiV1AdminMetricsGetWindow | Unset):  Default:
            GetAdminMetricsApiV1AdminMetricsGetWindow.VALUE_1.
        group_by (GroupBy | Unset): Safe enumeration of supported group_by dimensions.

            Values map to fixed SQL expressions via GROUP_BY_SQL below; no user string
            is ever interpolated into a query.

            Notes
            -----
            ``COMPLEXITY_TIER`` groups investigation jobs by the tier assigned during
            graph execution ("trivial" | "moderate" | "complex"). Rows where
            ``group_key`` is NULL are investigations that did not complete tier
            classification (e.g. early failure before the supervisor ran).

            ``DAY`` groups all event types by calendar day (UTC).

            ``EVENT_TYPE`` groups rows by event_type ("JobCompleted" | "IngestionCompleted" | ...).
        event_type (None | str | Unset): Optional event_type filter

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        HTTPValidationError | MetricsResponse
     """


    return (await asyncio_detailed(
        client=client,
window=window,
group_by=group_by,
event_type=event_type,

    )).parsed
