# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.alert_incident_response import AlertIncidentResponse
from ...models.http_validation_error import HTTPValidationError
from ...models.list_alert_incidents_api_v1_admin_alerts_get_status_type_0 import ListAlertIncidentsApiV1AdminAlertsGetStatusType0
from ...types import UNSET, Unset
from typing import cast



def _get_kwargs(
    *,
    status: ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> dict[str, Any]:
    

    

    params: dict[str, Any] = {}

    json_status: None | str | Unset
    if isinstance(status, Unset):
        json_status = UNSET
    elif isinstance(status, ListAlertIncidentsApiV1AdminAlertsGetStatusType0):
        json_status = status.value
    else:
        json_status = status
    params["status"] = json_status

    params["limit"] = limit

    params["offset"] = offset


    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}


    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/admin/alerts",
        "params": params,
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> HTTPValidationError | list[AlertIncidentResponse] | None:
    if response.status_code == 200:
        response_200 = []
        _response_200 = response.json()
        for response_200_item_data in (_response_200):
            response_200_item = AlertIncidentResponse.from_dict(response_200_item_data)



            response_200.append(response_200_item)

        return response_200

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[HTTPValidationError | list[AlertIncidentResponse]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    status: ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> Response[HTTPValidationError | list[AlertIncidentResponse]]:
    """ List alert incidents

     Returns current and historical alert incidents. Requires ADMIN role.

    Args:
        status (ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset): Filter by
            incident status
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[HTTPValidationError | list[AlertIncidentResponse]]
     """


    kwargs = _get_kwargs(
        status=status,
limit=limit,
offset=offset,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,
    status: ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> HTTPValidationError | list[AlertIncidentResponse] | None:
    """ List alert incidents

     Returns current and historical alert incidents. Requires ADMIN role.

    Args:
        status (ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset): Filter by
            incident status
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        HTTPValidationError | list[AlertIncidentResponse]
     """


    return sync_detailed(
        client=client,
status=status,
limit=limit,
offset=offset,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    status: ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> Response[HTTPValidationError | list[AlertIncidentResponse]]:
    """ List alert incidents

     Returns current and historical alert incidents. Requires ADMIN role.

    Args:
        status (ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset): Filter by
            incident status
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[HTTPValidationError | list[AlertIncidentResponse]]
     """


    kwargs = _get_kwargs(
        status=status,
limit=limit,
offset=offset,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    status: ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> HTTPValidationError | list[AlertIncidentResponse] | None:
    """ List alert incidents

     Returns current and historical alert incidents. Requires ADMIN role.

    Args:
        status (ListAlertIncidentsApiV1AdminAlertsGetStatusType0 | None | Unset): Filter by
            incident status
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        HTTPValidationError | list[AlertIncidentResponse]
     """


    return (await asyncio_detailed(
        client=client,
status=status,
limit=limit,
offset=offset,

    )).parsed
