# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.error_response import ErrorResponse
from ...models.hazard_event_response import HazardEventResponse
from ...models.http_validation_error import HTTPValidationError
from ...types import UNSET, Unset
from typing import cast



def _get_kwargs(
    *,
    event_type: None | str | Unset = UNSET,
    source: None | str | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> dict[str, Any]:
    

    

    params: dict[str, Any] = {}

    json_event_type: None | str | Unset
    if isinstance(event_type, Unset):
        json_event_type = UNSET
    else:
        json_event_type = event_type
    params["event_type"] = json_event_type

    json_source: None | str | Unset
    if isinstance(source, Unset):
        json_source = UNSET
    else:
        json_source = source
    params["source"] = json_source

    params["limit"] = limit

    params["offset"] = offset


    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}


    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/research/hazard-events",
        "params": params,
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> ErrorResponse | HTTPValidationError | list[HazardEventResponse] | None:
    if response.status_code == 200:
        response_200 = []
        _response_200 = response.json()
        for response_200_item_data in (_response_200):
            response_200_item = HazardEventResponse.from_dict(response_200_item_data)



            response_200.append(response_200_item)

        return response_200

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if response.status_code == 503:
        response_503 = ErrorResponse.from_dict(response.json())



        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ErrorResponse | HTTPValidationError | list[HazardEventResponse]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    event_type: None | str | Unset = UNSET,
    source: None | str | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> Response[ErrorResponse | HTTPValidationError | list[HazardEventResponse]]:
    """ List public hazard events

     Returns historical hazard events from public data sources (USGS, NOAA, FIRMS).

    Args:
        event_type (None | str | Unset): Filter by event type (e.g., earthquake)
        source (None | str | Unset): Filter by source (e.g., USGS)
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | HTTPValidationError | list[HazardEventResponse]]
     """


    kwargs = _get_kwargs(
        event_type=event_type,
source=source,
limit=limit,
offset=offset,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,
    event_type: None | str | Unset = UNSET,
    source: None | str | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> ErrorResponse | HTTPValidationError | list[HazardEventResponse] | None:
    """ List public hazard events

     Returns historical hazard events from public data sources (USGS, NOAA, FIRMS).

    Args:
        event_type (None | str | Unset): Filter by event type (e.g., earthquake)
        source (None | str | Unset): Filter by source (e.g., USGS)
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | HTTPValidationError | list[HazardEventResponse]
     """


    return sync_detailed(
        client=client,
event_type=event_type,
source=source,
limit=limit,
offset=offset,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    event_type: None | str | Unset = UNSET,
    source: None | str | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> Response[ErrorResponse | HTTPValidationError | list[HazardEventResponse]]:
    """ List public hazard events

     Returns historical hazard events from public data sources (USGS, NOAA, FIRMS).

    Args:
        event_type (None | str | Unset): Filter by event type (e.g., earthquake)
        source (None | str | Unset): Filter by source (e.g., USGS)
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | HTTPValidationError | list[HazardEventResponse]]
     """


    kwargs = _get_kwargs(
        event_type=event_type,
source=source,
limit=limit,
offset=offset,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    event_type: None | str | Unset = UNSET,
    source: None | str | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> ErrorResponse | HTTPValidationError | list[HazardEventResponse] | None:
    """ List public hazard events

     Returns historical hazard events from public data sources (USGS, NOAA, FIRMS).

    Args:
        event_type (None | str | Unset): Filter by event type (e.g., earthquake)
        source (None | str | Unset): Filter by source (e.g., USGS)
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | HTTPValidationError | list[HazardEventResponse]
     """


    return (await asyncio_detailed(
        client=client,
event_type=event_type,
source=source,
limit=limit,
offset=offset,

    )).parsed
