# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.error_response import ErrorResponse
from ...models.http_validation_error import HTTPValidationError
from ...models.list_public_research_patterns_api_v1_research_patterns_get_order import ListPublicResearchPatternsApiV1ResearchPatternsGetOrder
from ...models.list_public_research_patterns_api_v1_research_patterns_get_sort_by import ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy
from ...models.pattern_finding_response import PatternFindingResponse
from ...types import UNSET, Unset
from typing import cast



def _get_kwargs(
    *,
    event_type: None | str | Unset = UNSET,
    region: None | str | Unset = UNSET,
    time_window_days: int | None | Unset = UNSET,
    min_confidence: float | None | Unset = UNSET,
    sort_by: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE,
    order: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> dict[str, Any]:
    

    

    params: dict[str, Any] = {}

    json_event_type: None | str | Unset
    if isinstance(event_type, Unset):
        json_event_type = UNSET
    else:
        json_event_type = event_type
    params["event_type"] = json_event_type

    json_region: None | str | Unset
    if isinstance(region, Unset):
        json_region = UNSET
    else:
        json_region = region
    params["region"] = json_region

    json_time_window_days: int | None | Unset
    if isinstance(time_window_days, Unset):
        json_time_window_days = UNSET
    else:
        json_time_window_days = time_window_days
    params["time_window_days"] = json_time_window_days

    json_min_confidence: float | None | Unset
    if isinstance(min_confidence, Unset):
        json_min_confidence = UNSET
    else:
        json_min_confidence = min_confidence
    params["min_confidence"] = json_min_confidence

    json_sort_by: str | Unset = UNSET
    if not isinstance(sort_by, Unset):
        json_sort_by = sort_by.value

    params["sort_by"] = json_sort_by

    json_order: str | Unset = UNSET
    if not isinstance(order, Unset):
        json_order = order.value

    params["order"] = json_order

    params["limit"] = limit

    params["offset"] = offset


    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}


    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/research/patterns",
        "params": params,
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> ErrorResponse | HTTPValidationError | list[PatternFindingResponse] | None:
    if response.status_code == 200:
        response_200 = []
        _response_200 = response.json()
        for response_200_item_data in (_response_200):
            response_200_item = PatternFindingResponse.from_dict(response_200_item_data)



            response_200.append(response_200_item)

        return response_200

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if response.status_code == 503:
        response_503 = ErrorResponse.from_dict(response.json())



        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ErrorResponse | HTTPValidationError | list[PatternFindingResponse]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    event_type: None | str | Unset = UNSET,
    region: None | str | Unset = UNSET,
    time_window_days: int | None | Unset = UNSET,
    min_confidence: float | None | Unset = UNSET,
    sort_by: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE,
    order: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> Response[ErrorResponse | HTTPValidationError | list[PatternFindingResponse]]:
    """ List mined longitudinal research patterns

     Returns statistically-notable recurring co-occurrence patterns discovered across historical hazard
    events. Findings are computed periodically by background jobs and versioned to track historical
    confidence trends.

    Args:
        event_type (None | str | Unset): Filter by source or target event type (e.g. earthquake)
        region (None | str | Unset): Filter by geographic region label
        time_window_days (int | None | Unset): Filter by co-occurrence time window in days
        min_confidence (float | None | Unset): Filter by minimum statistical confidence
        sort_by (ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset): Sort attribute
            Default: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE.
        order (ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset): Sort direction
            Default: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC.
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | HTTPValidationError | list[PatternFindingResponse]]
     """


    kwargs = _get_kwargs(
        event_type=event_type,
region=region,
time_window_days=time_window_days,
min_confidence=min_confidence,
sort_by=sort_by,
order=order,
limit=limit,
offset=offset,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,
    event_type: None | str | Unset = UNSET,
    region: None | str | Unset = UNSET,
    time_window_days: int | None | Unset = UNSET,
    min_confidence: float | None | Unset = UNSET,
    sort_by: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE,
    order: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> ErrorResponse | HTTPValidationError | list[PatternFindingResponse] | None:
    """ List mined longitudinal research patterns

     Returns statistically-notable recurring co-occurrence patterns discovered across historical hazard
    events. Findings are computed periodically by background jobs and versioned to track historical
    confidence trends.

    Args:
        event_type (None | str | Unset): Filter by source or target event type (e.g. earthquake)
        region (None | str | Unset): Filter by geographic region label
        time_window_days (int | None | Unset): Filter by co-occurrence time window in days
        min_confidence (float | None | Unset): Filter by minimum statistical confidence
        sort_by (ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset): Sort attribute
            Default: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE.
        order (ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset): Sort direction
            Default: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC.
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | HTTPValidationError | list[PatternFindingResponse]
     """


    return sync_detailed(
        client=client,
event_type=event_type,
region=region,
time_window_days=time_window_days,
min_confidence=min_confidence,
sort_by=sort_by,
order=order,
limit=limit,
offset=offset,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    event_type: None | str | Unset = UNSET,
    region: None | str | Unset = UNSET,
    time_window_days: int | None | Unset = UNSET,
    min_confidence: float | None | Unset = UNSET,
    sort_by: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE,
    order: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> Response[ErrorResponse | HTTPValidationError | list[PatternFindingResponse]]:
    """ List mined longitudinal research patterns

     Returns statistically-notable recurring co-occurrence patterns discovered across historical hazard
    events. Findings are computed periodically by background jobs and versioned to track historical
    confidence trends.

    Args:
        event_type (None | str | Unset): Filter by source or target event type (e.g. earthquake)
        region (None | str | Unset): Filter by geographic region label
        time_window_days (int | None | Unset): Filter by co-occurrence time window in days
        min_confidence (float | None | Unset): Filter by minimum statistical confidence
        sort_by (ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset): Sort attribute
            Default: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE.
        order (ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset): Sort direction
            Default: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC.
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | HTTPValidationError | list[PatternFindingResponse]]
     """


    kwargs = _get_kwargs(
        event_type=event_type,
region=region,
time_window_days=time_window_days,
min_confidence=min_confidence,
sort_by=sort_by,
order=order,
limit=limit,
offset=offset,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    event_type: None | str | Unset = UNSET,
    region: None | str | Unset = UNSET,
    time_window_days: int | None | Unset = UNSET,
    min_confidence: float | None | Unset = UNSET,
    sort_by: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE,
    order: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset = ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> ErrorResponse | HTTPValidationError | list[PatternFindingResponse] | None:
    """ List mined longitudinal research patterns

     Returns statistically-notable recurring co-occurrence patterns discovered across historical hazard
    events. Findings are computed periodically by background jobs and versioned to track historical
    confidence trends.

    Args:
        event_type (None | str | Unset): Filter by source or target event type (e.g. earthquake)
        region (None | str | Unset): Filter by geographic region label
        time_window_days (int | None | Unset): Filter by co-occurrence time window in days
        min_confidence (float | None | Unset): Filter by minimum statistical confidence
        sort_by (ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy | Unset): Sort attribute
            Default: ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy.CONFIDENCE.
        order (ListPublicResearchPatternsApiV1ResearchPatternsGetOrder | Unset): Sort direction
            Default: ListPublicResearchPatternsApiV1ResearchPatternsGetOrder.DESC.
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | HTTPValidationError | list[PatternFindingResponse]
     """


    return (await asyncio_detailed(
        client=client,
event_type=event_type,
region=region,
time_window_days=time_window_days,
min_confidence=min_confidence,
sort_by=sort_by,
order=order,
limit=limit,
offset=offset,

    )).parsed
