# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.error_response import ErrorResponse
from ...models.http_validation_error import HTTPValidationError
from ...models.research_investigation_response import ResearchInvestigationResponse
from ...types import UNSET, Unset
from typing import cast
import datetime



def _get_kwargs(
    *,
    domain: None | str | Unset = UNSET,
    since: datetime.datetime | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> dict[str, Any]:
    

    

    params: dict[str, Any] = {}

    json_domain: None | str | Unset
    if isinstance(domain, Unset):
        json_domain = UNSET
    else:
        json_domain = domain
    params["domain"] = json_domain

    json_since: None | str | Unset
    if isinstance(since, Unset):
        json_since = UNSET
    elif isinstance(since, datetime.datetime):
        json_since = since.isoformat()
    else:
        json_since = since
    params["since"] = json_since

    params["limit"] = limit

    params["offset"] = offset


    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}


    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/research/investigations",
        "params": params,
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse] | None:
    if response.status_code == 200:
        response_200 = []
        _response_200 = response.json()
        for response_200_item_data in (_response_200):
            response_200_item = ResearchInvestigationResponse.from_dict(response_200_item_data)



            response_200.append(response_200_item)

        return response_200

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if response.status_code == 503:
        response_503 = ErrorResponse.from_dict(response.json())



        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    domain: None | str | Unset = UNSET,
    since: datetime.datetime | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> Response[ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse]]:
    """ List anonymized public research findings

     Returns aggregated, anonymized investigation findings. User identity (user_id) is strictly omitted
    (ADR-504). Raw query text is included ONLY if the submitter provided explicit consent.

    Args:
        domain (None | str | Unset): Filter by domain (e.g., seismic)
        since (datetime.datetime | None | Unset): Filter investigations since timestamp
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse]]
     """


    kwargs = _get_kwargs(
        domain=domain,
since=since,
limit=limit,
offset=offset,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,
    domain: None | str | Unset = UNSET,
    since: datetime.datetime | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse] | None:
    """ List anonymized public research findings

     Returns aggregated, anonymized investigation findings. User identity (user_id) is strictly omitted
    (ADR-504). Raw query text is included ONLY if the submitter provided explicit consent.

    Args:
        domain (None | str | Unset): Filter by domain (e.g., seismic)
        since (datetime.datetime | None | Unset): Filter investigations since timestamp
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse]
     """


    return sync_detailed(
        client=client,
domain=domain,
since=since,
limit=limit,
offset=offset,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    domain: None | str | Unset = UNSET,
    since: datetime.datetime | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> Response[ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse]]:
    """ List anonymized public research findings

     Returns aggregated, anonymized investigation findings. User identity (user_id) is strictly omitted
    (ADR-504). Raw query text is included ONLY if the submitter provided explicit consent.

    Args:
        domain (None | str | Unset): Filter by domain (e.g., seismic)
        since (datetime.datetime | None | Unset): Filter investigations since timestamp
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse]]
     """


    kwargs = _get_kwargs(
        domain=domain,
since=since,
limit=limit,
offset=offset,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    domain: None | str | Unset = UNSET,
    since: datetime.datetime | None | Unset = UNSET,
    limit: int | Unset = 50,
    offset: int | Unset = 0,

) -> ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse] | None:
    """ List anonymized public research findings

     Returns aggregated, anonymized investigation findings. User identity (user_id) is strictly omitted
    (ADR-504). Raw query text is included ONLY if the submitter provided explicit consent.

    Args:
        domain (None | str | Unset): Filter by domain (e.g., seismic)
        since (datetime.datetime | None | Unset): Filter investigations since timestamp
        limit (int | Unset):  Default: 50.
        offset (int | Unset):  Default: 0.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | HTTPValidationError | list[ResearchInvestigationResponse]
     """


    return (await asyncio_detailed(
        client=client,
domain=domain,
since=since,
limit=limit,
offset=offset,

    )).parsed
