# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.readiness_failure_response import ReadinessFailureResponse
from ...models.readiness_response import ReadinessResponse
from typing import cast



def _get_kwargs(
    
) -> dict[str, Any]:
    

    

    

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/health/ready",
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> ReadinessFailureResponse | ReadinessResponse | None:
    if response.status_code == 200:
        response_200 = ReadinessResponse.from_dict(response.json())



        return response_200

    if response.status_code == 503:
        response_503 = ReadinessFailureResponse.from_dict(response.json())



        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ReadinessFailureResponse | ReadinessResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,

) -> Response[ReadinessFailureResponse | ReadinessResponse]:
    """ Readiness probe

     Verifies the application is ready to receive traffic.  Checks database connectivity, PostGIS,
    pgvector, and Redis liveness.  Returns HTTP 200 on success; HTTP 503 when any dependency fails.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ReadinessFailureResponse | ReadinessResponse]
     """


    kwargs = _get_kwargs(
        
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,

) -> ReadinessFailureResponse | ReadinessResponse | None:
    """ Readiness probe

     Verifies the application is ready to receive traffic.  Checks database connectivity, PostGIS,
    pgvector, and Redis liveness.  Returns HTTP 200 on success; HTTP 503 when any dependency fails.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ReadinessFailureResponse | ReadinessResponse
     """


    return sync_detailed(
        client=client,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,

) -> Response[ReadinessFailureResponse | ReadinessResponse]:
    """ Readiness probe

     Verifies the application is ready to receive traffic.  Checks database connectivity, PostGIS,
    pgvector, and Redis liveness.  Returns HTTP 200 on success; HTTP 503 when any dependency fails.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ReadinessFailureResponse | ReadinessResponse]
     """


    kwargs = _get_kwargs(
        
    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,

) -> ReadinessFailureResponse | ReadinessResponse | None:
    """ Readiness probe

     Verifies the application is ready to receive traffic.  Checks database connectivity, PostGIS,
    pgvector, and Redis liveness.  Returns HTTP 200 on success; HTTP 503 when any dependency fails.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ReadinessFailureResponse | ReadinessResponse
     """


    return (await asyncio_detailed(
        client=client,

    )).parsed
