# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.user_register_request import UserRegisterRequest
from ...models.user_response import UserResponse
from typing import cast



def _get_kwargs(
    *,
    body: UserRegisterRequest,

) -> dict[str, Any]:
    headers: dict[str, Any] = {}


    

    

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v1/auth/register",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Any | UserResponse | None:
    if response.status_code == 201:
        response_201 = UserResponse.from_dict(response.json())



        return response_201

    if response.status_code == 409:
        response_409 = cast(Any, None)
        return response_409

    if response.status_code == 422:
        response_422 = cast(Any, None)
        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | UserResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: UserRegisterRequest,

) -> Response[Any | UserResponse]:
    """ Register

     Register a new user account.

    Enforces password strength policy and duplicate email checks.
    Issues a hashed verification token and triggers verification email delivery.

    Args:
        body (UserRegisterRequest): Payload to register a new user account.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | UserResponse]
     """


    kwargs = _get_kwargs(
        body=body,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,
    body: UserRegisterRequest,

) -> Any | UserResponse | None:
    """ Register

     Register a new user account.

    Enforces password strength policy and duplicate email checks.
    Issues a hashed verification token and triggers verification email delivery.

    Args:
        body (UserRegisterRequest): Payload to register a new user account.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | UserResponse
     """


    return sync_detailed(
        client=client,
body=body,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: UserRegisterRequest,

) -> Response[Any | UserResponse]:
    """ Register

     Register a new user account.

    Enforces password strength policy and duplicate email checks.
    Issues a hashed verification token and triggers verification email delivery.

    Args:
        body (UserRegisterRequest): Payload to register a new user account.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | UserResponse]
     """


    kwargs = _get_kwargs(
        body=body,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: UserRegisterRequest,

) -> Any | UserResponse | None:
    """ Register

     Register a new user account.

    Enforces password strength policy and duplicate email checks.
    Issues a hashed verification token and triggers verification email delivery.

    Args:
        body (UserRegisterRequest): Payload to register a new user account.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | UserResponse
     """


    return (await asyncio_detailed(
        client=client,
body=body,

    )).parsed
