# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.auth_message_response import AuthMessageResponse
from ...models.http_validation_error import HTTPValidationError
from ...models.password_reset_request_payload import PasswordResetRequestPayload
from typing import cast



def _get_kwargs(
    *,
    body: PasswordResetRequestPayload,

) -> dict[str, Any]:
    headers: dict[str, Any] = {}


    

    

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v1/auth/request-reset",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> AuthMessageResponse | HTTPValidationError | None:
    if response.status_code == 202:
        response_202 = AuthMessageResponse.from_dict(response.json())



        return response_202

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[AuthMessageResponse | HTTPValidationError]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: PasswordResetRequestPayload,

) -> Response[AuthMessageResponse | HTTPValidationError]:
    """ Request a password reset link

     Initiates password reset flow. Returns HTTP 202 with generic response regardless of whether the
    email exists to prevent account enumeration.

    Args:
        body (PasswordResetRequestPayload): Payload to initiate a password reset.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AuthMessageResponse | HTTPValidationError]
     """


    kwargs = _get_kwargs(
        body=body,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,
    body: PasswordResetRequestPayload,

) -> AuthMessageResponse | HTTPValidationError | None:
    """ Request a password reset link

     Initiates password reset flow. Returns HTTP 202 with generic response regardless of whether the
    email exists to prevent account enumeration.

    Args:
        body (PasswordResetRequestPayload): Payload to initiate a password reset.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AuthMessageResponse | HTTPValidationError
     """


    return sync_detailed(
        client=client,
body=body,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: PasswordResetRequestPayload,

) -> Response[AuthMessageResponse | HTTPValidationError]:
    """ Request a password reset link

     Initiates password reset flow. Returns HTTP 202 with generic response regardless of whether the
    email exists to prevent account enumeration.

    Args:
        body (PasswordResetRequestPayload): Payload to initiate a password reset.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AuthMessageResponse | HTTPValidationError]
     """


    kwargs = _get_kwargs(
        body=body,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: PasswordResetRequestPayload,

) -> AuthMessageResponse | HTTPValidationError | None:
    """ Request a password reset link

     Initiates password reset flow. Returns HTTP 202 with generic response regardless of whether the
    email exists to prevent account enumeration.

    Args:
        body (PasswordResetRequestPayload): Payload to initiate a password reset.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AuthMessageResponse | HTTPValidationError
     """


    return (await asyncio_detailed(
        client=client,
body=body,

    )).parsed
