# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.auth_message_response import AuthMessageResponse
from ...models.password_reset_confirm_payload import PasswordResetConfirmPayload
from typing import cast



def _get_kwargs(
    *,
    body: PasswordResetConfirmPayload,

) -> dict[str, Any]:
    headers: dict[str, Any] = {}


    

    

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/api/v1/auth/reset",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Any | AuthMessageResponse | None:
    if response.status_code == 200:
        response_200 = AuthMessageResponse.from_dict(response.json())



        return response_200

    if response.status_code == 400:
        response_400 = cast(Any, None)
        return response_400

    if response.status_code == 422:
        response_422 = cast(Any, None)
        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[Any | AuthMessageResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: PasswordResetConfirmPayload,

) -> Response[Any | AuthMessageResponse]:
    """ Reset password using valid reset token

     Reset account password using plaintext token and new password.

    Security features:
    1. Validates password strength policy.
    2. Hashes new password with Argon2id.
    3. Single transaction boundary: validates token, updates user password, consumes token,
       and invalidates ALL remaining active tokens for the user atomically (SELECT FOR UPDATE).

    Args:
        body (PasswordResetConfirmPayload): Payload to confirm password reset with raw token and
            new password.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | AuthMessageResponse]
     """


    kwargs = _get_kwargs(
        body=body,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    *,
    client: AuthenticatedClient | Client,
    body: PasswordResetConfirmPayload,

) -> Any | AuthMessageResponse | None:
    """ Reset password using valid reset token

     Reset account password using plaintext token and new password.

    Security features:
    1. Validates password strength policy.
    2. Hashes new password with Argon2id.
    3. Single transaction boundary: validates token, updates user password, consumes token,
       and invalidates ALL remaining active tokens for the user atomically (SELECT FOR UPDATE).

    Args:
        body (PasswordResetConfirmPayload): Payload to confirm password reset with raw token and
            new password.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | AuthMessageResponse
     """


    return sync_detailed(
        client=client,
body=body,

    ).parsed

async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: PasswordResetConfirmPayload,

) -> Response[Any | AuthMessageResponse]:
    """ Reset password using valid reset token

     Reset account password using plaintext token and new password.

    Security features:
    1. Validates password strength policy.
    2. Hashes new password with Argon2id.
    3. Single transaction boundary: validates token, updates user password, consumes token,
       and invalidates ALL remaining active tokens for the user atomically (SELECT FOR UPDATE).

    Args:
        body (PasswordResetConfirmPayload): Payload to confirm password reset with raw token and
            new password.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | AuthMessageResponse]
     """


    kwargs = _get_kwargs(
        body=body,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: PasswordResetConfirmPayload,

) -> Any | AuthMessageResponse | None:
    """ Reset password using valid reset token

     Reset account password using plaintext token and new password.

    Security features:
    1. Validates password strength policy.
    2. Hashes new password with Argon2id.
    3. Single transaction boundary: validates token, updates user password, consumes token,
       and invalidates ALL remaining active tokens for the user atomically (SELECT FOR UPDATE).

    Args:
        body (PasswordResetConfirmPayload): Payload to confirm password reset with raw token and
            new password.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | AuthMessageResponse
     """


    return (await asyncio_detailed(
        client=client,
body=body,

    )).parsed
