# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ...client import AuthenticatedClient, Client
from ...types import Response, UNSET
from ... import errors

from ...models.api_key_revoked_response import ApiKeyRevokedResponse
from ...models.http_validation_error import HTTPValidationError
from typing import cast



def _get_kwargs(
    key_id: str,

) -> dict[str, Any]:
    

    

    

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/api/v1/api-keys/{key_id}".format(key_id=quote(str(key_id), safe=""),),
    }


    return _kwargs



def _parse_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> ApiKeyRevokedResponse | HTTPValidationError | None:
    if response.status_code == 200:
        response_200 = ApiKeyRevokedResponse.from_dict(response.json())



        return response_200

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())



        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(*, client: AuthenticatedClient | Client, response: httpx.Response) -> Response[ApiKeyRevokedResponse | HTTPValidationError]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    key_id: str,
    *,
    client: AuthenticatedClient | Client,

) -> Response[ApiKeyRevokedResponse | HTTPValidationError]:
    """ Revoke an API Key

     Revokes an existing API key by key_id. Restricted to the owner or ADMIN.

    Args:
        key_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ApiKeyRevokedResponse | HTTPValidationError]
     """


    kwargs = _get_kwargs(
        key_id=key_id,

    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)

def sync(
    key_id: str,
    *,
    client: AuthenticatedClient | Client,

) -> ApiKeyRevokedResponse | HTTPValidationError | None:
    """ Revoke an API Key

     Revokes an existing API key by key_id. Restricted to the owner or ADMIN.

    Args:
        key_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ApiKeyRevokedResponse | HTTPValidationError
     """


    return sync_detailed(
        key_id=key_id,
client=client,

    ).parsed

async def asyncio_detailed(
    key_id: str,
    *,
    client: AuthenticatedClient | Client,

) -> Response[ApiKeyRevokedResponse | HTTPValidationError]:
    """ Revoke an API Key

     Revokes an existing API key by key_id. Restricted to the owner or ADMIN.

    Args:
        key_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ApiKeyRevokedResponse | HTTPValidationError]
     """


    kwargs = _get_kwargs(
        key_id=key_id,

    )

    response = await client.get_async_httpx_client().request(
        **kwargs
    )

    return _build_response(client=client, response=response)

async def asyncio(
    key_id: str,
    *,
    client: AuthenticatedClient | Client,

) -> ApiKeyRevokedResponse | HTTPValidationError | None:
    """ Revoke an API Key

     Revokes an existing API key by key_id. Restricted to the owner or ADMIN.

    Args:
        key_id (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ApiKeyRevokedResponse | HTTPValidationError
     """


    return (await asyncio_detailed(
        key_id=key_id,
client=client,

    )).parsed
