# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast
from uuid import UUID
import datetime






T = TypeVar("T", bound="AlertRuleResponse")



@_attrs_define
class AlertRuleResponse:
    """ API response model for an alert rule.

        Attributes:
            comparison (str):
            consecutive_cycles (int):
            created_at (datetime.datetime):
            id (UUID):
            is_enabled (bool):
            metric (str):
            name (str):
            severity (str):
            threshold (float):
            updated_at (datetime.datetime):
            window (str):
     """

    comparison: str
    consecutive_cycles: int
    created_at: datetime.datetime
    id: UUID
    is_enabled: bool
    metric: str
    name: str
    severity: str
    threshold: float
    updated_at: datetime.datetime
    window: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        comparison = self.comparison

        consecutive_cycles = self.consecutive_cycles

        created_at = self.created_at.isoformat()

        id = str(self.id)

        is_enabled = self.is_enabled

        metric = self.metric

        name = self.name

        severity = self.severity

        threshold = self.threshold

        updated_at = self.updated_at.isoformat()

        window = self.window


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "comparison": comparison,
            "consecutive_cycles": consecutive_cycles,
            "created_at": created_at,
            "id": id,
            "is_enabled": is_enabled,
            "metric": metric,
            "name": name,
            "severity": severity,
            "threshold": threshold,
            "updated_at": updated_at,
            "window": window,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        comparison = d.pop("comparison")

        consecutive_cycles = d.pop("consecutive_cycles")

        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))




        id = UUID(d.pop("id"))




        is_enabled = d.pop("is_enabled")

        metric = d.pop("metric")

        name = d.pop("name")

        severity = d.pop("severity")

        threshold = d.pop("threshold")

        updated_at = datetime.datetime.fromisoformat(d.pop("updated_at"))




        window = d.pop("window")

        alert_rule_response = cls(
            comparison=comparison,
            consecutive_cycles=consecutive_cycles,
            created_at=created_at,
            id=id,
            is_enabled=is_enabled,
            metric=metric,
            name=name,
            severity=severity,
            threshold=threshold,
            updated_at=updated_at,
            window=window,
        )


        alert_rule_response.additional_properties = d
        return alert_rule_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
