# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from enum import Enum

class AlertRuleSchemaSeverity(str, Enum):
    CRITICAL = "critical"
    WARNING = "warning"

    def __str__(self) -> str:
        return str(self.value)
