# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from enum import Enum

class AlertRuleSchemaWindow(str, Enum):
    VALUE_0 = "15m"
    VALUE_1 = "1h"
    VALUE_2 = "1d"
    VALUE_3 = "30d"

    def __str__(self) -> str:
        return str(self.value)
