# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
from uuid import UUID
import datetime






T = TypeVar("T", bound="AlertIncidentResponse")



@_attrs_define
class AlertIncidentResponse:
    """ API response model for an alert incident.

        Attributes:
            consecutive_violations (int):
            fired_at (datetime.datetime):
            id (UUID):
            last_value (float):
            resolved_at (datetime.datetime | None):
            rule_id (None | UUID):
            rule_name (str):
            severity (str):
            status (str):
            threshold (float):
            slo_name (None | str | Unset):
     """

    consecutive_violations: int
    fired_at: datetime.datetime
    id: UUID
    last_value: float
    resolved_at: datetime.datetime | None
    rule_id: None | UUID
    rule_name: str
    severity: str
    status: str
    threshold: float
    slo_name: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        consecutive_violations = self.consecutive_violations

        fired_at = self.fired_at.isoformat()

        id = str(self.id)

        last_value = self.last_value

        resolved_at: None | str
        if isinstance(self.resolved_at, datetime.datetime):
            resolved_at = self.resolved_at.isoformat()
        else:
            resolved_at = self.resolved_at

        rule_id: None | str
        if isinstance(self.rule_id, UUID):
            rule_id = str(self.rule_id)
        else:
            rule_id = self.rule_id

        rule_name = self.rule_name

        severity = self.severity

        status = self.status

        threshold = self.threshold

        slo_name: None | str | Unset
        if isinstance(self.slo_name, Unset):
            slo_name = UNSET
        else:
            slo_name = self.slo_name


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "consecutive_violations": consecutive_violations,
            "fired_at": fired_at,
            "id": id,
            "last_value": last_value,
            "resolved_at": resolved_at,
            "rule_id": rule_id,
            "rule_name": rule_name,
            "severity": severity,
            "status": status,
            "threshold": threshold,
        })
        if slo_name is not UNSET:
            field_dict["slo_name"] = slo_name

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        consecutive_violations = d.pop("consecutive_violations")

        fired_at = datetime.datetime.fromisoformat(d.pop("fired_at"))




        id = UUID(d.pop("id"))




        last_value = d.pop("last_value")

        def _parse_resolved_at(data: object) -> datetime.datetime | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                resolved_at_type_0 = datetime.datetime.fromisoformat(data)



                return resolved_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None, data)

        resolved_at = _parse_resolved_at(d.pop("resolved_at"))


        def _parse_rule_id(data: object) -> None | UUID:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                rule_id_type_0 = UUID(data)



                return rule_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | UUID, data)

        rule_id = _parse_rule_id(d.pop("rule_id"))


        rule_name = d.pop("rule_name")

        severity = d.pop("severity")

        status = d.pop("status")

        threshold = d.pop("threshold")

        def _parse_slo_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        slo_name = _parse_slo_name(d.pop("slo_name", UNSET))


        alert_incident_response = cls(
            consecutive_violations=consecutive_violations,
            fired_at=fired_at,
            id=id,
            last_value=last_value,
            resolved_at=resolved_at,
            rule_id=rule_id,
            rule_name=rule_name,
            severity=severity,
            status=status,
            threshold=threshold,
            slo_name=slo_name,
        )


        alert_incident_response.additional_properties = d
        return alert_incident_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
