# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..models.alert_rule_schema_comparison import AlertRuleSchemaComparison
from ..models.alert_rule_schema_severity import AlertRuleSchemaSeverity
from ..models.alert_rule_schema_window import AlertRuleSchemaWindow
from ..types import UNSET, Unset
from typing import cast






T = TypeVar("T", bound="AlertRuleSchema")



@_attrs_define
class AlertRuleSchema:
    """ Pydantic schema for creating or updating an alert rule.

        Attributes:
            metric (str):
            name (str):
            threshold (float):
            comparison (AlertRuleSchemaComparison | Unset):  Default: AlertRuleSchemaComparison.GT.
            consecutive_cycles (int | Unset):  Default: 1.
            is_enabled (bool | Unset):  Default: True.
            severity (AlertRuleSchemaSeverity | Unset):  Default: AlertRuleSchemaSeverity.WARNING.
            slo_name (None | str | Unset):
            window (AlertRuleSchemaWindow | Unset):  Default: AlertRuleSchemaWindow.VALUE_0.
     """

    metric: str
    name: str
    threshold: float
    comparison: AlertRuleSchemaComparison | Unset = AlertRuleSchemaComparison.GT
    consecutive_cycles: int | Unset = 1
    is_enabled: bool | Unset = True
    severity: AlertRuleSchemaSeverity | Unset = AlertRuleSchemaSeverity.WARNING
    slo_name: None | str | Unset = UNSET
    window: AlertRuleSchemaWindow | Unset = AlertRuleSchemaWindow.VALUE_0
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        metric = self.metric

        name = self.name

        threshold = self.threshold

        comparison: str | Unset = UNSET
        if not isinstance(self.comparison, Unset):
            comparison = self.comparison.value


        consecutive_cycles = self.consecutive_cycles

        is_enabled = self.is_enabled

        severity: str | Unset = UNSET
        if not isinstance(self.severity, Unset):
            severity = self.severity.value


        slo_name: None | str | Unset
        if isinstance(self.slo_name, Unset):
            slo_name = UNSET
        else:
            slo_name = self.slo_name

        window: str | Unset = UNSET
        if not isinstance(self.window, Unset):
            window = self.window.value



        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "metric": metric,
            "name": name,
            "threshold": threshold,
        })
        if comparison is not UNSET:
            field_dict["comparison"] = comparison
        if consecutive_cycles is not UNSET:
            field_dict["consecutive_cycles"] = consecutive_cycles
        if is_enabled is not UNSET:
            field_dict["is_enabled"] = is_enabled
        if severity is not UNSET:
            field_dict["severity"] = severity
        if slo_name is not UNSET:
            field_dict["slo_name"] = slo_name
        if window is not UNSET:
            field_dict["window"] = window

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        metric = d.pop("metric")

        name = d.pop("name")

        threshold = d.pop("threshold")

        _comparison = d.pop("comparison", UNSET)
        comparison: AlertRuleSchemaComparison | Unset
        if isinstance(_comparison,  Unset):
            comparison = UNSET
        else:
            comparison = AlertRuleSchemaComparison(_comparison)




        consecutive_cycles = d.pop("consecutive_cycles", UNSET)

        is_enabled = d.pop("is_enabled", UNSET)

        _severity = d.pop("severity", UNSET)
        severity: AlertRuleSchemaSeverity | Unset
        if isinstance(_severity,  Unset):
            severity = UNSET
        else:
            severity = AlertRuleSchemaSeverity(_severity)




        def _parse_slo_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        slo_name = _parse_slo_name(d.pop("slo_name", UNSET))


        _window = d.pop("window", UNSET)
        window: AlertRuleSchemaWindow | Unset
        if isinstance(_window,  Unset):
            window = UNSET
        else:
            window = AlertRuleSchemaWindow(_window)




        alert_rule_schema = cls(
            metric=metric,
            name=name,
            threshold=threshold,
            comparison=comparison,
            consecutive_cycles=consecutive_cycles,
            is_enabled=is_enabled,
            severity=severity,
            slo_name=slo_name,
            window=window,
        )


        alert_rule_schema.additional_properties = d
        return alert_rule_schema

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
