# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast
import datetime

if TYPE_CHECKING:
  from ..models.backup_record_schema_verification_metadata import BackupRecordSchemaVerificationMetadata





T = TypeVar("T", bound="BackupRecordSchema")



@_attrs_define
class BackupRecordSchema:
    """ API response schema for a database backup audit record.

        Attributes:
            backup_id (str):
            checksum (str):
            completed_at (datetime.datetime | None):
            created_at (datetime.datetime):
            duration_ms (float):
            error_details (None | str):
            postgres_version (str):
            size_bytes (int):
            status (str):
            storage_location (str):
            verification_metadata (BackupRecordSchemaVerificationMetadata):
     """

    backup_id: str
    checksum: str
    completed_at: datetime.datetime | None
    created_at: datetime.datetime
    duration_ms: float
    error_details: None | str
    postgres_version: str
    size_bytes: int
    status: str
    storage_location: str
    verification_metadata: BackupRecordSchemaVerificationMetadata
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.backup_record_schema_verification_metadata import BackupRecordSchemaVerificationMetadata
        backup_id = self.backup_id

        checksum = self.checksum

        completed_at: None | str
        if isinstance(self.completed_at, datetime.datetime):
            completed_at = self.completed_at.isoformat()
        else:
            completed_at = self.completed_at

        created_at = self.created_at.isoformat()

        duration_ms = self.duration_ms

        error_details: None | str
        error_details = self.error_details

        postgres_version = self.postgres_version

        size_bytes = self.size_bytes

        status = self.status

        storage_location = self.storage_location

        verification_metadata = self.verification_metadata.to_dict()


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "backup_id": backup_id,
            "checksum": checksum,
            "completed_at": completed_at,
            "created_at": created_at,
            "duration_ms": duration_ms,
            "error_details": error_details,
            "postgres_version": postgres_version,
            "size_bytes": size_bytes,
            "status": status,
            "storage_location": storage_location,
            "verification_metadata": verification_metadata,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.backup_record_schema_verification_metadata import BackupRecordSchemaVerificationMetadata
        d = dict(src_dict)
        backup_id = d.pop("backup_id")

        checksum = d.pop("checksum")

        def _parse_completed_at(data: object) -> datetime.datetime | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                completed_at_type_0 = datetime.datetime.fromisoformat(data)



                return completed_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None, data)

        completed_at = _parse_completed_at(d.pop("completed_at"))


        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))




        duration_ms = d.pop("duration_ms")

        def _parse_error_details(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        error_details = _parse_error_details(d.pop("error_details"))


        postgres_version = d.pop("postgres_version")

        size_bytes = d.pop("size_bytes")

        status = d.pop("status")

        storage_location = d.pop("storage_location")

        verification_metadata = BackupRecordSchemaVerificationMetadata.from_dict(d.pop("verification_metadata"))




        backup_record_schema = cls(
            backup_id=backup_id,
            checksum=checksum,
            completed_at=completed_at,
            created_at=created_at,
            duration_ms=duration_ms,
            error_details=error_details,
            postgres_version=postgres_version,
            size_bytes=size_bytes,
            status=status,
            storage_location=storage_location,
            verification_metadata=verification_metadata,
        )


        backup_record_schema.additional_properties = d
        return backup_record_schema

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
