# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from enum import Enum

class GetAdminMetricsApiV1AdminMetricsGetWindow(str, Enum):
    VALUE_0 = "1d"
    VALUE_1 = "7d"
    VALUE_2 = "30d"
    VALUE_3 = "90d"

    def __str__(self) -> str:
        return str(self.value)
