# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from enum import Enum

class GroupBy(str, Enum):
    COMPLEXITY_TIER = "complexity_tier"
    DAY = "day"

    def __str__(self) -> str:
        return str(self.value)
