# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast
from uuid import UUID
import datetime






T = TypeVar("T", bound="HazardEventResponse")



@_attrs_define
class HazardEventResponse:
    """ Public hazard event schema.

        Attributes:
            created_at (datetime.datetime):
            details (None | str):
            event_date (datetime.datetime):
            event_type (str):
            external_id (None | str):
            id (UUID):
            region_label (None | str):
            source (None | str):
     """

    created_at: datetime.datetime
    details: None | str
    event_date: datetime.datetime
    event_type: str
    external_id: None | str
    id: UUID
    region_label: None | str
    source: None | str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        created_at = self.created_at.isoformat()

        details: None | str
        details = self.details

        event_date = self.event_date.isoformat()

        event_type = self.event_type

        external_id: None | str
        external_id = self.external_id

        id = str(self.id)

        region_label: None | str
        region_label = self.region_label

        source: None | str
        source = self.source


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "created_at": created_at,
            "details": details,
            "event_date": event_date,
            "event_type": event_type,
            "external_id": external_id,
            "id": id,
            "region_label": region_label,
            "source": source,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))




        def _parse_details(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        details = _parse_details(d.pop("details"))


        event_date = datetime.datetime.fromisoformat(d.pop("event_date"))




        event_type = d.pop("event_type")

        def _parse_external_id(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        external_id = _parse_external_id(d.pop("external_id"))


        id = UUID(d.pop("id"))




        def _parse_region_label(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        region_label = _parse_region_label(d.pop("region_label"))


        def _parse_source(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        source = _parse_source(d.pop("source"))


        hazard_event_response = cls(
            created_at=created_at,
            details=details,
            event_date=event_date,
            event_type=event_type,
            external_id=external_id,
            id=id,
            region_label=region_label,
            source=source,
        )


        hazard_event_response.additional_properties = d
        return hazard_event_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
