# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset







T = TypeVar("T", bound="HistoricalScalingTelemetrySchema")



@_attrs_define
class HistoricalScalingTelemetrySchema:
    """ Historical scaling telemetry summary for M5 trigger validation.

        Attributes:
            avg_queue_depth (float):
            avg_worker_utilization_pct (float):
            max_queue_depth (int):
            max_worker_utilization_pct (float):
            sample_count (int):
            scaling_verdict (str):
            sustained_queue_depth_breach (bool):
            sustained_trigger_satisfied (bool):
            sustained_utilization_breach (bool):
            threshold_crossed_at_least_once (bool):
            triggers_met (bool):
            window (str):
     """

    avg_queue_depth: float
    avg_worker_utilization_pct: float
    max_queue_depth: int
    max_worker_utilization_pct: float
    sample_count: int
    scaling_verdict: str
    sustained_queue_depth_breach: bool
    sustained_trigger_satisfied: bool
    sustained_utilization_breach: bool
    threshold_crossed_at_least_once: bool
    triggers_met: bool
    window: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        avg_queue_depth = self.avg_queue_depth

        avg_worker_utilization_pct = self.avg_worker_utilization_pct

        max_queue_depth = self.max_queue_depth

        max_worker_utilization_pct = self.max_worker_utilization_pct

        sample_count = self.sample_count

        scaling_verdict = self.scaling_verdict

        sustained_queue_depth_breach = self.sustained_queue_depth_breach

        sustained_trigger_satisfied = self.sustained_trigger_satisfied

        sustained_utilization_breach = self.sustained_utilization_breach

        threshold_crossed_at_least_once = self.threshold_crossed_at_least_once

        triggers_met = self.triggers_met

        window = self.window


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "avg_queue_depth": avg_queue_depth,
            "avg_worker_utilization_pct": avg_worker_utilization_pct,
            "max_queue_depth": max_queue_depth,
            "max_worker_utilization_pct": max_worker_utilization_pct,
            "sample_count": sample_count,
            "scaling_verdict": scaling_verdict,
            "sustained_queue_depth_breach": sustained_queue_depth_breach,
            "sustained_trigger_satisfied": sustained_trigger_satisfied,
            "sustained_utilization_breach": sustained_utilization_breach,
            "threshold_crossed_at_least_once": threshold_crossed_at_least_once,
            "triggers_met": triggers_met,
            "window": window,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        avg_queue_depth = d.pop("avg_queue_depth")

        avg_worker_utilization_pct = d.pop("avg_worker_utilization_pct")

        max_queue_depth = d.pop("max_queue_depth")

        max_worker_utilization_pct = d.pop("max_worker_utilization_pct")

        sample_count = d.pop("sample_count")

        scaling_verdict = d.pop("scaling_verdict")

        sustained_queue_depth_breach = d.pop("sustained_queue_depth_breach")

        sustained_trigger_satisfied = d.pop("sustained_trigger_satisfied")

        sustained_utilization_breach = d.pop("sustained_utilization_breach")

        threshold_crossed_at_least_once = d.pop("threshold_crossed_at_least_once")

        triggers_met = d.pop("triggers_met")

        window = d.pop("window")

        historical_scaling_telemetry_schema = cls(
            avg_queue_depth=avg_queue_depth,
            avg_worker_utilization_pct=avg_worker_utilization_pct,
            max_queue_depth=max_queue_depth,
            max_worker_utilization_pct=max_worker_utilization_pct,
            sample_count=sample_count,
            scaling_verdict=scaling_verdict,
            sustained_queue_depth_breach=sustained_queue_depth_breach,
            sustained_trigger_satisfied=sustained_trigger_satisfied,
            sustained_utilization_breach=sustained_utilization_breach,
            threshold_crossed_at_least_once=threshold_crossed_at_least_once,
            triggers_met=triggers_met,
            window=window,
        )


        historical_scaling_telemetry_schema.additional_properties = d
        return historical_scaling_telemetry_schema

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
