# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
from uuid import UUID

if TYPE_CHECKING:
  from ..models.trace_edge import TraceEdge
  from ..models.trace_metadata import TraceMetadata
  from ..models.trace_node import TraceNode
  from ..models.trace_summary import TraceSummary





T = TypeVar("T", bound="InvestigationTraceResponse")



@_attrs_define
class InvestigationTraceResponse:
    """ Response payload for GET /api/v1/investigations/{id}/trace.

        Attributes:
            edges (list[TraceEdge]):
            investigation_id (UUID):
            metadata (TraceMetadata): Metadata container including contract schema_version and generated_at timestamp.
            nodes (list[TraceNode]):
            summary (TraceSummary): High-level summary of execution trace statistics.
            schema_version (str | Unset):  Default: '1.0'.
     """

    edges: list[TraceEdge]
    investigation_id: UUID
    metadata: TraceMetadata
    nodes: list[TraceNode]
    summary: TraceSummary
    schema_version: str | Unset = '1.0'
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.trace_edge import TraceEdge
        from ..models.trace_metadata import TraceMetadata
        from ..models.trace_node import TraceNode
        from ..models.trace_summary import TraceSummary
        edges = []
        for edges_item_data in self.edges:
            edges_item = edges_item_data.to_dict()
            edges.append(edges_item)



        investigation_id = str(self.investigation_id)

        metadata = self.metadata.to_dict()

        nodes = []
        for nodes_item_data in self.nodes:
            nodes_item = nodes_item_data.to_dict()
            nodes.append(nodes_item)



        summary = self.summary.to_dict()

        schema_version = self.schema_version


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "edges": edges,
            "investigation_id": investigation_id,
            "metadata": metadata,
            "nodes": nodes,
            "summary": summary,
        })
        if schema_version is not UNSET:
            field_dict["schema_version"] = schema_version

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.trace_edge import TraceEdge
        from ..models.trace_metadata import TraceMetadata
        from ..models.trace_node import TraceNode
        from ..models.trace_summary import TraceSummary
        d = dict(src_dict)
        edges = []
        _edges = d.pop("edges")
        for edges_item_data in (_edges):
            edges_item = TraceEdge.from_dict(edges_item_data)



            edges.append(edges_item)


        investigation_id = UUID(d.pop("investigation_id"))




        metadata = TraceMetadata.from_dict(d.pop("metadata"))




        nodes = []
        _nodes = d.pop("nodes")
        for nodes_item_data in (_nodes):
            nodes_item = TraceNode.from_dict(nodes_item_data)



            nodes.append(nodes_item)


        summary = TraceSummary.from_dict(d.pop("summary"))




        schema_version = d.pop("schema_version", UNSET)

        investigation_trace_response = cls(
            edges=edges,
            investigation_id=investigation_id,
            metadata=metadata,
            nodes=nodes,
            summary=summary,
            schema_version=schema_version,
        )


        investigation_trace_response.additional_properties = d
        return investigation_trace_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
