# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import Literal, cast
from uuid import UUID






T = TypeVar("T", bound="InvestigationCreateResponse")



@_attrs_define
class InvestigationCreateResponse:
    """ Payload returned upon successfully queuing an investigation.

        Attributes:
            investigation_id (UUID):
            poll_url (str):
            status (Literal['accepted']):
            stream_url (str):
     """

    investigation_id: UUID
    poll_url: str
    status: Literal['accepted']
    stream_url: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        investigation_id = str(self.investigation_id)

        poll_url = self.poll_url

        status = self.status

        stream_url = self.stream_url


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "investigation_id": investigation_id,
            "poll_url": poll_url,
            "status": status,
            "stream_url": stream_url,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        investigation_id = UUID(d.pop("investigation_id"))




        poll_url = d.pop("poll_url")

        status = cast(Literal['accepted'] , d.pop("status"))
        if status != 'accepted':
            raise ValueError(f"status must match const 'accepted', got '{status}'")

        stream_url = d.pop("stream_url")

        investigation_create_response = cls(
            investigation_id=investigation_id,
            poll_url=poll_url,
            status=status,
            stream_url=stream_url,
        )


        investigation_create_response.additional_properties = d
        return investigation_create_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
