# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset






T = TypeVar("T", bound="InvestigationCreateRequest")



@_attrs_define
class InvestigationCreateRequest:
    """ Payload to create a new investigation query.

        Attributes:
            query (str):
            consent_public_research (bool | Unset): Explicit opt-in consent to include anonymized investigation query text
                in public research dataset (ADR-504). Default: False.
     """

    query: str
    consent_public_research: bool | Unset = False
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        query = self.query

        consent_public_research = self.consent_public_research


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "query": query,
        })
        if consent_public_research is not UNSET:
            field_dict["consent_public_research"] = consent_public_research

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        query = d.pop("query")

        consent_public_research = d.pop("consent_public_research", UNSET)

        investigation_create_request = cls(
            query=query,
            consent_public_research=consent_public_research,
        )


        investigation_create_request.additional_properties = d
        return investigation_create_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
