# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
from uuid import UUID
import datetime

if TYPE_CHECKING:
  from ..models.investigation_status_response_execution_trace_type_0 import InvestigationStatusResponseExecutionTraceType0





T = TypeVar("T", bound="InvestigationStatusResponse")



@_attrs_define
class InvestigationStatusResponse:
    """ Current execution state of an investigation.

        Attributes:
            answer (None | str):
            completed_at (datetime.datetime | None):
            complexity_tier (None | str):
            confidence (float | None):
            created_at (datetime.datetime):
            execution_trace (InvestigationStatusResponseExecutionTraceType0 | None):
            investigation_id (UUID):
            status (str):
            evidence_gaps (list[str] | Unset):
     """

    answer: None | str
    completed_at: datetime.datetime | None
    complexity_tier: None | str
    confidence: float | None
    created_at: datetime.datetime
    execution_trace: InvestigationStatusResponseExecutionTraceType0 | None
    investigation_id: UUID
    status: str
    evidence_gaps: list[str] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.investigation_status_response_execution_trace_type_0 import InvestigationStatusResponseExecutionTraceType0
        answer: None | str
        answer = self.answer

        completed_at: None | str
        if isinstance(self.completed_at, datetime.datetime):
            completed_at = self.completed_at.isoformat()
        else:
            completed_at = self.completed_at

        complexity_tier: None | str
        complexity_tier = self.complexity_tier

        confidence: float | None
        confidence = self.confidence

        created_at = self.created_at.isoformat()

        execution_trace: dict[str, Any] | None
        if isinstance(self.execution_trace, InvestigationStatusResponseExecutionTraceType0):
            execution_trace = self.execution_trace.to_dict()
        else:
            execution_trace = self.execution_trace

        investigation_id = str(self.investigation_id)

        status = self.status

        evidence_gaps: list[str] | Unset = UNSET
        if not isinstance(self.evidence_gaps, Unset):
            evidence_gaps = self.evidence_gaps




        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "answer": answer,
            "completed_at": completed_at,
            "complexity_tier": complexity_tier,
            "confidence": confidence,
            "created_at": created_at,
            "execution_trace": execution_trace,
            "investigation_id": investigation_id,
            "status": status,
        })
        if evidence_gaps is not UNSET:
            field_dict["evidence_gaps"] = evidence_gaps

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.investigation_status_response_execution_trace_type_0 import InvestigationStatusResponseExecutionTraceType0
        d = dict(src_dict)
        def _parse_answer(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        answer = _parse_answer(d.pop("answer"))


        def _parse_completed_at(data: object) -> datetime.datetime | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                completed_at_type_0 = datetime.datetime.fromisoformat(data)



                return completed_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None, data)

        completed_at = _parse_completed_at(d.pop("completed_at"))


        def _parse_complexity_tier(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        complexity_tier = _parse_complexity_tier(d.pop("complexity_tier"))


        def _parse_confidence(data: object) -> float | None:
            if data is None:
                return data
            return cast(float | None, data)

        confidence = _parse_confidence(d.pop("confidence"))


        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))




        def _parse_execution_trace(data: object) -> InvestigationStatusResponseExecutionTraceType0 | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                execution_trace_type_0 = InvestigationStatusResponseExecutionTraceType0.from_dict(data)



                return execution_trace_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(InvestigationStatusResponseExecutionTraceType0 | None, data)

        execution_trace = _parse_execution_trace(d.pop("execution_trace"))


        investigation_id = UUID(d.pop("investigation_id"))




        status = d.pop("status")

        evidence_gaps = cast(list[str], d.pop("evidence_gaps", UNSET))


        investigation_status_response = cls(
            answer=answer,
            completed_at=completed_at,
            complexity_tier=complexity_tier,
            confidence=confidence,
            created_at=created_at,
            execution_trace=execution_trace,
            investigation_id=investigation_id,
            status=status,
            evidence_gaps=evidence_gaps,
        )


        investigation_status_response.additional_properties = d
        return investigation_status_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
