# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from enum import Enum

class ListPublicResearchPatternsApiV1ResearchPatternsGetSortBy(str, Enum):
    CONFIDENCE = "confidence"
    LIFT = "lift"
    MINED_AT = "mined_at"
    SUPPORT_COUNT = "support_count"

    def __str__(self) -> str:
        return str(self.value)
