# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast






T = TypeVar("T", bound="MetricRollupSchema")



@_attrs_define
class MetricRollupSchema:
    """ Serialised form of a MetricRollup for API consumers.

        Attributes:
            avg_cost_estimate (float):
            count (int):
            group_key (None | str):
            p50_latency_ms (float):
            p95_latency_ms (float):
            success_rate (float):
     """

    avg_cost_estimate: float
    count: int
    group_key: None | str
    p50_latency_ms: float
    p95_latency_ms: float
    success_rate: float
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        avg_cost_estimate = self.avg_cost_estimate

        count = self.count

        group_key: None | str
        group_key = self.group_key

        p50_latency_ms = self.p50_latency_ms

        p95_latency_ms = self.p95_latency_ms

        success_rate = self.success_rate


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "avg_cost_estimate": avg_cost_estimate,
            "count": count,
            "group_key": group_key,
            "p50_latency_ms": p50_latency_ms,
            "p95_latency_ms": p95_latency_ms,
            "success_rate": success_rate,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        avg_cost_estimate = d.pop("avg_cost_estimate")

        count = d.pop("count")

        def _parse_group_key(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        group_key = _parse_group_key(d.pop("group_key"))


        p50_latency_ms = d.pop("p50_latency_ms")

        p95_latency_ms = d.pop("p95_latency_ms")

        success_rate = d.pop("success_rate")

        metric_rollup_schema = cls(
            avg_cost_estimate=avg_cost_estimate,
            count=count,
            group_key=group_key,
            p50_latency_ms=p50_latency_ms,
            p95_latency_ms=p95_latency_ms,
            success_rate=success_rate,
        )


        metric_rollup_schema.additional_properties = d
        return metric_rollup_schema

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
