# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast

if TYPE_CHECKING:
  from ..models.metric_rollup_schema import MetricRollupSchema





T = TypeVar("T", bound="MetricsResponse")



@_attrs_define
class MetricsResponse:
    """ Container for metrics rollups and advisory worker pool scaling metrics.

        Attributes:
            group_by (str):
            queue_depth (int):
            recommended_pool_size (int):
            rollups (list[MetricRollupSchema]):
            window (str):
            worker_utilization_pct (float):
            event_type (None | str | Unset):
            generated_at (str | Unset): ISO 8601 UTC timestamp when metrics rollups were generated.
     """

    group_by: str
    queue_depth: int
    recommended_pool_size: int
    rollups: list[MetricRollupSchema]
    window: str
    worker_utilization_pct: float
    event_type: None | str | Unset = UNSET
    generated_at: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.metric_rollup_schema import MetricRollupSchema
        group_by = self.group_by

        queue_depth = self.queue_depth

        recommended_pool_size = self.recommended_pool_size

        rollups = []
        for rollups_item_data in self.rollups:
            rollups_item = rollups_item_data.to_dict()
            rollups.append(rollups_item)



        window = self.window

        worker_utilization_pct = self.worker_utilization_pct

        event_type: None | str | Unset
        if isinstance(self.event_type, Unset):
            event_type = UNSET
        else:
            event_type = self.event_type

        generated_at = self.generated_at


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "group_by": group_by,
            "queue_depth": queue_depth,
            "recommended_pool_size": recommended_pool_size,
            "rollups": rollups,
            "window": window,
            "worker_utilization_pct": worker_utilization_pct,
        })
        if event_type is not UNSET:
            field_dict["event_type"] = event_type
        if generated_at is not UNSET:
            field_dict["generated_at"] = generated_at

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.metric_rollup_schema import MetricRollupSchema
        d = dict(src_dict)
        group_by = d.pop("group_by")

        queue_depth = d.pop("queue_depth")

        recommended_pool_size = d.pop("recommended_pool_size")

        rollups = []
        _rollups = d.pop("rollups")
        for rollups_item_data in (_rollups):
            rollups_item = MetricRollupSchema.from_dict(rollups_item_data)



            rollups.append(rollups_item)


        window = d.pop("window")

        worker_utilization_pct = d.pop("worker_utilization_pct")

        def _parse_event_type(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        event_type = _parse_event_type(d.pop("event_type", UNSET))


        generated_at = d.pop("generated_at", UNSET)

        metrics_response = cls(
            group_by=group_by,
            queue_depth=queue_depth,
            recommended_pool_size=recommended_pool_size,
            rollups=rollups,
            window=window,
            worker_utilization_pct=worker_utilization_pct,
            event_type=event_type,
            generated_at=generated_at,
        )


        metrics_response.additional_properties = d
        return metrics_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
