# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset







T = TypeVar("T", bound="PasswordResetConfirmPayload")



@_attrs_define
class PasswordResetConfirmPayload:
    """ Payload to confirm password reset with raw token and new password.

        Attributes:
            new_password (str):
            token (str):
     """

    new_password: str
    token: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        new_password = self.new_password

        token = self.token


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "new_password": new_password,
            "token": token,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        new_password = d.pop("new_password")

        token = d.pop("token")

        password_reset_confirm_payload = cls(
            new_password=new_password,
            token=token,
        )


        password_reset_confirm_payload.additional_properties = d
        return password_reset_confirm_payload

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
