# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast
from uuid import UUID
import datetime

if TYPE_CHECKING:
  from ..models.pattern_finding_response_uncertainty import PatternFindingResponseUncertainty





T = TypeVar("T", bound="PatternFindingResponse")



@_attrs_define
class PatternFindingResponse:
    """ Public research longitudinal pattern finding schema.

        Attributes:
            algorithm_version (str):
            baseline_rate (float):
            created_at (datetime.datetime):
            description (str):
            id (UUID):
            lift (float):
            mined_at (datetime.datetime):
            observed_rate (float):
            pattern_hash (str):
            region_label (None | str):
            source_event_type (str):
            statistical_confidence (float):
            support_count (int):
            supporting_event_ids (list[str]):
            target_event_type (str):
            time_window_days (int):
            total_source_events (int):
            total_target_events (int):
            uncertainty (PatternFindingResponseUncertainty):
            version (int):
     """

    algorithm_version: str
    baseline_rate: float
    created_at: datetime.datetime
    description: str
    id: UUID
    lift: float
    mined_at: datetime.datetime
    observed_rate: float
    pattern_hash: str
    region_label: None | str
    source_event_type: str
    statistical_confidence: float
    support_count: int
    supporting_event_ids: list[str]
    target_event_type: str
    time_window_days: int
    total_source_events: int
    total_target_events: int
    uncertainty: PatternFindingResponseUncertainty
    version: int
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.pattern_finding_response_uncertainty import PatternFindingResponseUncertainty
        algorithm_version = self.algorithm_version

        baseline_rate = self.baseline_rate

        created_at = self.created_at.isoformat()

        description = self.description

        id = str(self.id)

        lift = self.lift

        mined_at = self.mined_at.isoformat()

        observed_rate = self.observed_rate

        pattern_hash = self.pattern_hash

        region_label: None | str
        region_label = self.region_label

        source_event_type = self.source_event_type

        statistical_confidence = self.statistical_confidence

        support_count = self.support_count

        supporting_event_ids = self.supporting_event_ids



        target_event_type = self.target_event_type

        time_window_days = self.time_window_days

        total_source_events = self.total_source_events

        total_target_events = self.total_target_events

        uncertainty = self.uncertainty.to_dict()

        version = self.version


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "algorithm_version": algorithm_version,
            "baseline_rate": baseline_rate,
            "created_at": created_at,
            "description": description,
            "id": id,
            "lift": lift,
            "mined_at": mined_at,
            "observed_rate": observed_rate,
            "pattern_hash": pattern_hash,
            "region_label": region_label,
            "source_event_type": source_event_type,
            "statistical_confidence": statistical_confidence,
            "support_count": support_count,
            "supporting_event_ids": supporting_event_ids,
            "target_event_type": target_event_type,
            "time_window_days": time_window_days,
            "total_source_events": total_source_events,
            "total_target_events": total_target_events,
            "uncertainty": uncertainty,
            "version": version,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.pattern_finding_response_uncertainty import PatternFindingResponseUncertainty
        d = dict(src_dict)
        algorithm_version = d.pop("algorithm_version")

        baseline_rate = d.pop("baseline_rate")

        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))




        description = d.pop("description")

        id = UUID(d.pop("id"))




        lift = d.pop("lift")

        mined_at = datetime.datetime.fromisoformat(d.pop("mined_at"))




        observed_rate = d.pop("observed_rate")

        pattern_hash = d.pop("pattern_hash")

        def _parse_region_label(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        region_label = _parse_region_label(d.pop("region_label"))


        source_event_type = d.pop("source_event_type")

        statistical_confidence = d.pop("statistical_confidence")

        support_count = d.pop("support_count")

        supporting_event_ids = cast(list[str], d.pop("supporting_event_ids"))


        target_event_type = d.pop("target_event_type")

        time_window_days = d.pop("time_window_days")

        total_source_events = d.pop("total_source_events")

        total_target_events = d.pop("total_target_events")

        uncertainty = PatternFindingResponseUncertainty.from_dict(d.pop("uncertainty"))




        version = d.pop("version")

        pattern_finding_response = cls(
            algorithm_version=algorithm_version,
            baseline_rate=baseline_rate,
            created_at=created_at,
            description=description,
            id=id,
            lift=lift,
            mined_at=mined_at,
            observed_rate=observed_rate,
            pattern_hash=pattern_hash,
            region_label=region_label,
            source_event_type=source_event_type,
            statistical_confidence=statistical_confidence,
            support_count=support_count,
            supporting_event_ids=supporting_event_ids,
            target_event_type=target_event_type,
            time_window_days=time_window_days,
            total_source_events=total_source_events,
            total_target_events=total_target_events,
            uncertainty=uncertainty,
            version=version,
        )


        pattern_finding_response.additional_properties = d
        return pattern_finding_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
