# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset







T = TypeVar("T", bound="ReadinessResponse")



@_attrs_define
class ReadinessResponse:
    """ Response body for GET /api/v1/health/ready (success path).

        Attributes:
            app_version (str):
            database (str):
            redis (str):
            schema_version (str):
            status (str):
     """

    app_version: str
    database: str
    redis: str
    schema_version: str
    status: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        app_version = self.app_version

        database = self.database

        redis = self.redis

        schema_version = self.schema_version

        status = self.status


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "app_version": app_version,
            "database": database,
            "redis": redis,
            "schema_version": schema_version,
            "status": status,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        app_version = d.pop("app_version")

        database = d.pop("database")

        redis = d.pop("redis")

        schema_version = d.pop("schema_version")

        status = d.pop("status")

        readiness_response = cls(
            app_version=app_version,
            database=database,
            redis=redis,
            schema_version=schema_version,
            status=status,
        )


        readiness_response.additional_properties = d
        return readiness_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
