# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset







T = TypeVar("T", bound="ReadinessFailureResponse")



@_attrs_define
class ReadinessFailureResponse:
    """ Response body for GET /api/v1/health/ready (failure path, HTTP 503).

        Attributes:
            failing_dependency (str):
            reason (str):
            status (str):
     """

    failing_dependency: str
    reason: str
    status: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        failing_dependency = self.failing_dependency

        reason = self.reason

        status = self.status


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "failing_dependency": failing_dependency,
            "reason": reason,
            "status": status,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        failing_dependency = d.pop("failing_dependency")

        reason = d.pop("reason")

        status = d.pop("status")

        readiness_failure_response = cls(
            failing_dependency=failing_dependency,
            reason=reason,
            status=status,
        )


        readiness_failure_response.additional_properties = d
        return readiness_failure_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
