# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
from uuid import UUID
import datetime

if TYPE_CHECKING:
  from ..models.research_investigation_response_execution_trace_type_0 import ResearchInvestigationResponseExecutionTraceType0





T = TypeVar("T", bound="ResearchInvestigationResponse")



@_attrs_define
class ResearchInvestigationResponse:
    """ Anonymized investigation schema returned to public research consumers.

        Attributes:
            complexity_tier (None | str):
            confidence_summary (float | None):
            consent_public_research (bool):
            created_at (datetime.datetime):
            domains_involved (list[str]):
            investigation_id (UUID):
            query_category (str):
            completed_at (datetime.datetime | None | Unset):
            execution_trace (None | ResearchInvestigationResponseExecutionTraceType0 | Unset):
            query_text (None | str | Unset):
     """

    complexity_tier: None | str
    confidence_summary: float | None
    consent_public_research: bool
    created_at: datetime.datetime
    domains_involved: list[str]
    investigation_id: UUID
    query_category: str
    completed_at: datetime.datetime | None | Unset = UNSET
    execution_trace: None | ResearchInvestigationResponseExecutionTraceType0 | Unset = UNSET
    query_text: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.research_investigation_response_execution_trace_type_0 import ResearchInvestigationResponseExecutionTraceType0
        complexity_tier: None | str
        complexity_tier = self.complexity_tier

        confidence_summary: float | None
        confidence_summary = self.confidence_summary

        consent_public_research = self.consent_public_research

        created_at = self.created_at.isoformat()

        domains_involved = self.domains_involved



        investigation_id = str(self.investigation_id)

        query_category = self.query_category

        completed_at: None | str | Unset
        if isinstance(self.completed_at, Unset):
            completed_at = UNSET
        elif isinstance(self.completed_at, datetime.datetime):
            completed_at = self.completed_at.isoformat()
        else:
            completed_at = self.completed_at

        execution_trace: dict[str, Any] | None | Unset
        if isinstance(self.execution_trace, Unset):
            execution_trace = UNSET
        elif isinstance(self.execution_trace, ResearchInvestigationResponseExecutionTraceType0):
            execution_trace = self.execution_trace.to_dict()
        else:
            execution_trace = self.execution_trace

        query_text: None | str | Unset
        if isinstance(self.query_text, Unset):
            query_text = UNSET
        else:
            query_text = self.query_text


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "complexity_tier": complexity_tier,
            "confidence_summary": confidence_summary,
            "consent_public_research": consent_public_research,
            "created_at": created_at,
            "domains_involved": domains_involved,
            "investigation_id": investigation_id,
            "query_category": query_category,
        })
        if completed_at is not UNSET:
            field_dict["completed_at"] = completed_at
        if execution_trace is not UNSET:
            field_dict["execution_trace"] = execution_trace
        if query_text is not UNSET:
            field_dict["query_text"] = query_text

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.research_investigation_response_execution_trace_type_0 import ResearchInvestigationResponseExecutionTraceType0
        d = dict(src_dict)
        def _parse_complexity_tier(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        complexity_tier = _parse_complexity_tier(d.pop("complexity_tier"))


        def _parse_confidence_summary(data: object) -> float | None:
            if data is None:
                return data
            return cast(float | None, data)

        confidence_summary = _parse_confidence_summary(d.pop("confidence_summary"))


        consent_public_research = d.pop("consent_public_research")

        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))




        domains_involved = cast(list[str], d.pop("domains_involved"))


        investigation_id = UUID(d.pop("investigation_id"))




        query_category = d.pop("query_category")

        def _parse_completed_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                completed_at_type_0 = datetime.datetime.fromisoformat(data)



                return completed_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        completed_at = _parse_completed_at(d.pop("completed_at", UNSET))


        def _parse_execution_trace(data: object) -> None | ResearchInvestigationResponseExecutionTraceType0 | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                execution_trace_type_0 = ResearchInvestigationResponseExecutionTraceType0.from_dict(data)



                return execution_trace_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | ResearchInvestigationResponseExecutionTraceType0 | Unset, data)

        execution_trace = _parse_execution_trace(d.pop("execution_trace", UNSET))


        def _parse_query_text(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        query_text = _parse_query_text(d.pop("query_text", UNSET))


        research_investigation_response = cls(
            complexity_tier=complexity_tier,
            confidence_summary=confidence_summary,
            consent_public_research=consent_public_research,
            created_at=created_at,
            domains_involved=domains_involved,
            investigation_id=investigation_id,
            query_category=query_category,
            completed_at=completed_at,
            execution_trace=execution_trace,
            query_text=query_text,
        )


        research_investigation_response.additional_properties = d
        return research_investigation_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
