# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast
import datetime

if TYPE_CHECKING:
  from ..models.restore_drill_record_schema_discrepancies import RestoreDrillRecordSchemaDiscrepancies





T = TypeVar("T", bound="RestoreDrillRecordSchema")



@_attrs_define
class RestoreDrillRecordSchema:
    """ API response schema for a restore drill audit record.

        Attributes:
            backup_id (str):
            checksum_match (bool):
            completed_at (datetime.datetime | None):
            discrepancies (RestoreDrillRecordSchemaDiscrepancies):
            drill_id (str):
            duration_ms (float):
            error_details (None | str):
            migration_version_match (bool):
            row_counts_match (bool):
            started_at (datetime.datetime):
            status (str):
     """

    backup_id: str
    checksum_match: bool
    completed_at: datetime.datetime | None
    discrepancies: RestoreDrillRecordSchemaDiscrepancies
    drill_id: str
    duration_ms: float
    error_details: None | str
    migration_version_match: bool
    row_counts_match: bool
    started_at: datetime.datetime
    status: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.restore_drill_record_schema_discrepancies import RestoreDrillRecordSchemaDiscrepancies
        backup_id = self.backup_id

        checksum_match = self.checksum_match

        completed_at: None | str
        if isinstance(self.completed_at, datetime.datetime):
            completed_at = self.completed_at.isoformat()
        else:
            completed_at = self.completed_at

        discrepancies = self.discrepancies.to_dict()

        drill_id = self.drill_id

        duration_ms = self.duration_ms

        error_details: None | str
        error_details = self.error_details

        migration_version_match = self.migration_version_match

        row_counts_match = self.row_counts_match

        started_at = self.started_at.isoformat()

        status = self.status


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "backup_id": backup_id,
            "checksum_match": checksum_match,
            "completed_at": completed_at,
            "discrepancies": discrepancies,
            "drill_id": drill_id,
            "duration_ms": duration_ms,
            "error_details": error_details,
            "migration_version_match": migration_version_match,
            "row_counts_match": row_counts_match,
            "started_at": started_at,
            "status": status,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.restore_drill_record_schema_discrepancies import RestoreDrillRecordSchemaDiscrepancies
        d = dict(src_dict)
        backup_id = d.pop("backup_id")

        checksum_match = d.pop("checksum_match")

        def _parse_completed_at(data: object) -> datetime.datetime | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                completed_at_type_0 = datetime.datetime.fromisoformat(data)



                return completed_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None, data)

        completed_at = _parse_completed_at(d.pop("completed_at"))


        discrepancies = RestoreDrillRecordSchemaDiscrepancies.from_dict(d.pop("discrepancies"))




        drill_id = d.pop("drill_id")

        duration_ms = d.pop("duration_ms")

        def _parse_error_details(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        error_details = _parse_error_details(d.pop("error_details"))


        migration_version_match = d.pop("migration_version_match")

        row_counts_match = d.pop("row_counts_match")

        started_at = datetime.datetime.fromisoformat(d.pop("started_at"))




        status = d.pop("status")

        restore_drill_record_schema = cls(
            backup_id=backup_id,
            checksum_match=checksum_match,
            completed_at=completed_at,
            discrepancies=discrepancies,
            drill_id=drill_id,
            duration_ms=duration_ms,
            error_details=error_details,
            migration_version_match=migration_version_match,
            row_counts_match=row_counts_match,
            started_at=started_at,
            status=status,
        )


        restore_drill_record_schema.additional_properties = d
        return restore_drill_record_schema

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
