# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast
from uuid import UUID
import datetime






T = TypeVar("T", bound="TraceMetadata")



@_attrs_define
class TraceMetadata:
    """ Metadata container including contract schema_version and generated_at timestamp.

        Attributes:
            created_at (datetime.datetime):
            investigation_id (UUID):
            status (str):
            completed_at (datetime.datetime | None | Unset):
            complexity_tier (None | str | Unset):
            confidence (float | None | Unset):
            edge_count (int | Unset):  Default: 0.
            generated_at (datetime.datetime | Unset):
            has_collaboration (bool | Unset):  Default: False.
            has_degraded_mode (bool | Unset):  Default: False.
            has_replan (bool | Unset):  Default: False.
            node_count (int | Unset):  Default: 0.
            schema_version (str | Unset):  Default: '1.0'.
     """

    created_at: datetime.datetime
    investigation_id: UUID
    status: str
    completed_at: datetime.datetime | None | Unset = UNSET
    complexity_tier: None | str | Unset = UNSET
    confidence: float | None | Unset = UNSET
    edge_count: int | Unset = 0
    generated_at: datetime.datetime | Unset = UNSET
    has_collaboration: bool | Unset = False
    has_degraded_mode: bool | Unset = False
    has_replan: bool | Unset = False
    node_count: int | Unset = 0
    schema_version: str | Unset = '1.0'
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        created_at = self.created_at.isoformat()

        investigation_id = str(self.investigation_id)

        status = self.status

        completed_at: None | str | Unset
        if isinstance(self.completed_at, Unset):
            completed_at = UNSET
        elif isinstance(self.completed_at, datetime.datetime):
            completed_at = self.completed_at.isoformat()
        else:
            completed_at = self.completed_at

        complexity_tier: None | str | Unset
        if isinstance(self.complexity_tier, Unset):
            complexity_tier = UNSET
        else:
            complexity_tier = self.complexity_tier

        confidence: float | None | Unset
        if isinstance(self.confidence, Unset):
            confidence = UNSET
        else:
            confidence = self.confidence

        edge_count = self.edge_count

        generated_at: str | Unset = UNSET
        if not isinstance(self.generated_at, Unset):
            generated_at = self.generated_at.isoformat()

        has_collaboration = self.has_collaboration

        has_degraded_mode = self.has_degraded_mode

        has_replan = self.has_replan

        node_count = self.node_count

        schema_version = self.schema_version


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "created_at": created_at,
            "investigation_id": investigation_id,
            "status": status,
        })
        if completed_at is not UNSET:
            field_dict["completed_at"] = completed_at
        if complexity_tier is not UNSET:
            field_dict["complexity_tier"] = complexity_tier
        if confidence is not UNSET:
            field_dict["confidence"] = confidence
        if edge_count is not UNSET:
            field_dict["edge_count"] = edge_count
        if generated_at is not UNSET:
            field_dict["generated_at"] = generated_at
        if has_collaboration is not UNSET:
            field_dict["has_collaboration"] = has_collaboration
        if has_degraded_mode is not UNSET:
            field_dict["has_degraded_mode"] = has_degraded_mode
        if has_replan is not UNSET:
            field_dict["has_replan"] = has_replan
        if node_count is not UNSET:
            field_dict["node_count"] = node_count
        if schema_version is not UNSET:
            field_dict["schema_version"] = schema_version

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))




        investigation_id = UUID(d.pop("investigation_id"))




        status = d.pop("status")

        def _parse_completed_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                completed_at_type_0 = datetime.datetime.fromisoformat(data)



                return completed_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        completed_at = _parse_completed_at(d.pop("completed_at", UNSET))


        def _parse_complexity_tier(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        complexity_tier = _parse_complexity_tier(d.pop("complexity_tier", UNSET))


        def _parse_confidence(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        confidence = _parse_confidence(d.pop("confidence", UNSET))


        edge_count = d.pop("edge_count", UNSET)

        _generated_at = d.pop("generated_at", UNSET)
        generated_at: datetime.datetime | Unset
        if isinstance(_generated_at,  Unset):
            generated_at = UNSET
        else:
            generated_at = datetime.datetime.fromisoformat(_generated_at)




        has_collaboration = d.pop("has_collaboration", UNSET)

        has_degraded_mode = d.pop("has_degraded_mode", UNSET)

        has_replan = d.pop("has_replan", UNSET)

        node_count = d.pop("node_count", UNSET)

        schema_version = d.pop("schema_version", UNSET)

        trace_metadata = cls(
            created_at=created_at,
            investigation_id=investigation_id,
            status=status,
            completed_at=completed_at,
            complexity_tier=complexity_tier,
            confidence=confidence,
            edge_count=edge_count,
            generated_at=generated_at,
            has_collaboration=has_collaboration,
            has_degraded_mode=has_degraded_mode,
            has_replan=has_replan,
            node_count=node_count,
            schema_version=schema_version,
        )


        trace_metadata.additional_properties = d
        return trace_metadata

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
