# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast






T = TypeVar("T", bound="TraceSummary")



@_attrs_define
class TraceSummary:
    """ High-level summary of execution trace statistics.

        Attributes:
            collaboration_event_count (int | Unset):  Default: 0.
            critic_flag_count (int | Unset):  Default: 0.
            degraded_sources (list[str] | Unset):
            evidence_count (int | Unset):  Default: 0.
            replan_count (int | Unset):  Default: 0.
     """

    collaboration_event_count: int | Unset = 0
    critic_flag_count: int | Unset = 0
    degraded_sources: list[str] | Unset = UNSET
    evidence_count: int | Unset = 0
    replan_count: int | Unset = 0
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        collaboration_event_count = self.collaboration_event_count

        critic_flag_count = self.critic_flag_count

        degraded_sources: list[str] | Unset = UNSET
        if not isinstance(self.degraded_sources, Unset):
            degraded_sources = self.degraded_sources



        evidence_count = self.evidence_count

        replan_count = self.replan_count


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
        })
        if collaboration_event_count is not UNSET:
            field_dict["collaboration_event_count"] = collaboration_event_count
        if critic_flag_count is not UNSET:
            field_dict["critic_flag_count"] = critic_flag_count
        if degraded_sources is not UNSET:
            field_dict["degraded_sources"] = degraded_sources
        if evidence_count is not UNSET:
            field_dict["evidence_count"] = evidence_count
        if replan_count is not UNSET:
            field_dict["replan_count"] = replan_count

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        collaboration_event_count = d.pop("collaboration_event_count", UNSET)

        critic_flag_count = d.pop("critic_flag_count", UNSET)

        degraded_sources = cast(list[str], d.pop("degraded_sources", UNSET))


        evidence_count = d.pop("evidence_count", UNSET)

        replan_count = d.pop("replan_count", UNSET)

        trace_summary = cls(
            collaboration_event_count=collaboration_event_count,
            critic_flag_count=critic_flag_count,
            degraded_sources=degraded_sources,
            evidence_count=evidence_count,
            replan_count=replan_count,
        )


        trace_summary.additional_properties = d
        return trace_summary

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
