# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from typing import cast

if TYPE_CHECKING:
  from ..models.trace_node_details import TraceNodeDetails





T = TypeVar("T", bound="TraceNode")



@_attrs_define
class TraceNode:
    """ A node in the reasoning execution graph.

        Attributes:
            id (str):
            label (str):
            type_ (str):
            details (TraceNodeDetails | Unset):
            status (str | Unset):  Default: 'completed'.
            timestamp (None | str | Unset):
     """

    id: str
    label: str
    type_: str
    details: TraceNodeDetails | Unset = UNSET
    status: str | Unset = 'completed'
    timestamp: None | str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        from ..models.trace_node_details import TraceNodeDetails
        id = self.id

        label = self.label

        type_ = self.type_

        details: dict[str, Any] | Unset = UNSET
        if not isinstance(self.details, Unset):
            details = self.details.to_dict()

        status = self.status

        timestamp: None | str | Unset
        if isinstance(self.timestamp, Unset):
            timestamp = UNSET
        else:
            timestamp = self.timestamp


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "id": id,
            "label": label,
            "type": type_,
        })
        if details is not UNSET:
            field_dict["details"] = details
        if status is not UNSET:
            field_dict["status"] = status
        if timestamp is not UNSET:
            field_dict["timestamp"] = timestamp

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.trace_node_details import TraceNodeDetails
        d = dict(src_dict)
        id = d.pop("id")

        label = d.pop("label")

        type_ = d.pop("type")

        _details = d.pop("details", UNSET)
        details: TraceNodeDetails | Unset
        if isinstance(_details,  Unset):
            details = UNSET
        else:
            details = TraceNodeDetails.from_dict(_details)




        status = d.pop("status", UNSET)

        def _parse_timestamp(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        timestamp = _parse_timestamp(d.pop("timestamp", UNSET))


        trace_node = cls(
            id=id,
            label=label,
            type_=type_,
            details=details,
            status=status,
            timestamp=timestamp,
        )


        trace_node.additional_properties = d
        return trace_node

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
