# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY
# Regenerate using: python scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from typing import cast
from uuid import UUID
import datetime






T = TypeVar("T", bound="UserResponse")



@_attrs_define
class UserResponse:
    """ Public user identity response payload.

        Attributes:
            created_at (datetime.datetime):
            email (str):
            full_name (None | str):
            id (UUID):
            is_active (bool):
            is_verified (bool):
            last_login_at (datetime.datetime | None):
            role (str):
     """

    created_at: datetime.datetime
    email: str
    full_name: None | str
    id: UUID
    is_active: bool
    is_verified: bool
    last_login_at: datetime.datetime | None
    role: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        created_at = self.created_at.isoformat()

        email = self.email

        full_name: None | str
        full_name = self.full_name

        id = str(self.id)

        is_active = self.is_active

        is_verified = self.is_verified

        last_login_at: None | str
        if isinstance(self.last_login_at, datetime.datetime):
            last_login_at = self.last_login_at.isoformat()
        else:
            last_login_at = self.last_login_at

        role = self.role


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "created_at": created_at,
            "email": email,
            "full_name": full_name,
            "id": id,
            "is_active": is_active,
            "is_verified": is_verified,
            "last_login_at": last_login_at,
            "role": role,
        })

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))




        email = d.pop("email")

        def _parse_full_name(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        full_name = _parse_full_name(d.pop("full_name"))


        id = UUID(d.pop("id"))




        is_active = d.pop("is_active")

        is_verified = d.pop("is_verified")

        def _parse_last_login_at(data: object) -> datetime.datetime | None:
            if data is None:
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                last_login_at_type_0 = datetime.datetime.fromisoformat(data)



                return last_login_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None, data)

        last_login_at = _parse_last_login_at(d.pop("last_login_at"))


        role = d.pop("role")

        user_response = cls(
            created_at=created_at,
            email=email,
            full_name=full_name,
            id=id,
            is_active=is_active,
            is_verified=is_verified,
            last_login_at=last_login_at,
            role=role,
        )


        user_response.additional_properties = d
        return user_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
