"""Script to deterministically generate the GaiaOS Python SDK from the OpenAPI spec."""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
import time
from pathlib import Path

# Ensure repository root is in sys.path
_repo_root = Path(__file__).resolve().parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from scripts.generate_openapi_spec import write_openapi_spec  # noqa: E402

HEADER_BANNER = (
    "# AUTO-GENERATED BY openapi-python-client – DO NOT EDIT DIRECTLY\n"
    "# Regenerate using: python scripts/generate_sdk.py\n\n"
)


def _force_remove_readonly(func, path, exc_info):
    """Clear the read-only attribute and retry removing path on Windows."""
    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except Exception:
        pass


def safe_remove_dir(target_dir: Path) -> None:
    """Safely remove a directory tree, handling Windows permission locks."""
    if not target_dir.exists():
        return

    for _ in range(3):
        try:
            shutil.rmtree(target_dir, onexc=_force_remove_readonly)
            break
        except Exception:
            time.sleep(0.3)


def generate_sdk() -> None:
    """Generate OpenAPI spec and output Python SDK into sdk/python/gaiaos_sdk/_generated."""
    print("Step 1: Generating OpenAPI spec...")
    spec_path = write_openapi_spec()
    print(f"OpenAPI spec written to {spec_path}")

    sdk_dir = _repo_root / "sdk" / "python"
    generated_dir = sdk_dir / "gaiaos_sdk" / "_generated"
    config_path = sdk_dir / "openapi-python-client.yaml"

    if generated_dir.exists():
        print(f"Removing existing generated directory at {generated_dir}...")
        safe_remove_dir(generated_dir)
        time.sleep(0.2)

    generated_dir.parent.mkdir(parents=True, exist_ok=True)

    print("Step 2: Invoking openapi-python-client...")
    cmd = [
        sys.executable,
        "-m",
        "openapi_python_client",
        "generate",
        "--path",
        str(spec_path),
        "--output-path",
        str(generated_dir),
        "--meta",
        "none",
        "--overwrite",
        "--config",
        str(config_path),
    ]

    res = subprocess.run(cmd, cwd=str(_repo_root), capture_output=True, text=True)
    if res.returncode != 0:
        print(f"Generator stdout:\n{res.stdout}")
        print(f"Generator stderr:\n{res.stderr}")
        raise RuntimeError(f"openapi-python-client failed with code {res.returncode}")

    print("Step 3: Injecting auto-generated header banners...")
    py_files = sorted(generated_dir.rglob("*.py"))
    modified_count = 0
    for py_file in py_files:
        content = py_file.read_text(encoding="utf-8")
        if not content.startswith("# AUTO-GENERATED BY openapi-python-client"):
            py_file.write_text(HEADER_BANNER + content, encoding="utf-8", newline="\n")
            modified_count += 1

    print(
        f"Successfully generated SDK at {generated_dir} "
        f"({len(py_files)} Python files present, {modified_count} newly annotated)."
    )


if __name__ == "__main__":
    generate_sdk()
