"""Regenerate requirements lockfiles via pip dependency resolution.

Uses pip's dependency resolver (pip install --dry-run --report) to produce
reproducible lockfiles directly from requirements/*.txt without modifying files by text replacement.

Canonical Lockfile Environment: Linux (Ubuntu 22.04+ / ubuntu-latest) + Python 3.12.

Reachability Policy:
A dependency is retained if it is reachable through at least one requirement whose
environment marker evaluates true in the canonical Linux environment.
"""

from __future__ import annotations

import json
import logging
import subprocess
import sys
import tempfile
from pathlib import Path

from packaging.markers import UndefinedComparison, UndefinedEnvironmentName
from packaging.requirements import InvalidRequirement, Requirement
from packaging.utils import canonicalize_name

logger = logging.getLogger("regenerate_lockfiles")

REPO_ROOT = Path(__file__).resolve().parent.parent

BASE_LOCK_HEADER = (
    "# GaiaOS Phase 5 — Production Runtime Lockfile\n"
    "# Generated by pip dependency resolution (scripts/regenerate_lockfiles.py)."
)

DEV_LOCK_HEADER = (
    "# GaiaOS Phase 5 — Development & Testing Lockfile\n"
    "# Generated by pip dependency resolution (scripts/regenerate_lockfiles.py)."
)

# Canonical environment context matching production and CI runner
CANONICAL_ENV: dict[str, str] = {
    "sys_platform": "linux",
    "platform_system": "Linux",
    "os_name": "posix",
    "python_version": "3.12",
}


def is_valid_for_canonical_env(req: Requirement) -> bool:
    """Evaluate if a Requirement marker is valid in the canonical Linux environment.

    Tests marker evaluation across potential extra flags to isolate platform-specific
    markers (e.g. sys_platform == 'win32') from feature extra markers.
    """
    if req.marker is None:
        return True

    # Test common extra markers; if marker evaluates True under Linux for any extra, it is valid
    for extra_val in ["", "standard", "crypto", "email", "timezone", "asyncio", "postgres", "cffi"]:
        env = {**CANONICAL_ENV, "extra": extra_val}
        try:
            if req.marker.evaluate(env):
                return True
        except (UndefinedComparison, UndefinedEnvironmentName) as exc:
            logger.debug("Undefined marker variable in '%s': %s", req, exc)
            continue
    return False


def resolve_lockfile_with_pip(req_txt_path: Path, header_comment: str) -> str:
    """Run pip dependency resolution for req_txt_path and return formatted lockfile content."""
    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tmp:
        report_json_path = Path(tmp.name)

    try:
        cmd = [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--dry-run",
            "--report",
            str(report_json_path),
            "-r",
            str(req_txt_path),
            "--ignore-installed",
        ]
        res = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(
                f"pip dependency resolution failed for {req_txt_path}:\n{res.stderr}"
            )

        with open(report_json_path, encoding="utf-8") as f:
            data = json.load(f)

        install_items = data.get("install", [])

        # 1. Collect all dependency requirement markers declared across installed packages
        dep_map: dict[str, list[Requirement]] = {}
        for item in install_items:
            metadata = item.get("metadata", {})
            reqs = metadata.get("requires_dist", [])
            for r_str in reqs:
                try:
                    req = Requirement(r_str)
                    canon = canonicalize_name(req.name)
                    dep_map.setdefault(canon, []).append(req)
                except InvalidRequirement as exc:
                    logger.debug("Skipping unparseable dependency specifier '%s': %s", r_str, exc)

        # 2. Reachability Policy: Retain dependency if reachable via >=1 valid canonical requirement
        packages: dict[str, str] = {}
        for item in install_items:
            metadata = item.get("metadata", {})
            name = metadata.get("name")
            version = metadata.get("version")
            if not name or not version:
                continue

            canon = canonicalize_name(name)
            is_direct = item.get("requested", False)

            if is_direct:
                packages[name] = version
                continue

            incoming_reqs = dep_map.get(canon, [])
            valid_in_canonical = False

            if not incoming_reqs:
                valid_in_canonical = True
            else:
                for req in incoming_reqs:
                    if is_valid_for_canonical_env(req):
                        valid_in_canonical = True
                        break

            if valid_in_canonical:
                packages[name] = version

        # Format lockfile sorted by package name
        lines = [header_comment.strip(), ""]
        for pkg_name in sorted(packages.keys(), key=lambda s: s.lower()):
            lines.append(f"{pkg_name}=={packages[pkg_name]}")
        lines.append("")

        return "\n".join(lines)

    finally:
        if report_json_path.exists():
            report_json_path.unlink()


def main() -> int:
    check_mode = "--check" in sys.argv
    if "--verbose" in sys.argv or "-v" in sys.argv:
        logging.basicConfig(level=logging.DEBUG)

    base_txt = REPO_ROOT / "requirements" / "base.txt"
    base_lock = REPO_ROOT / "requirements" / "base.lock"
    dev_txt = REPO_ROOT / "requirements" / "dev.txt"
    dev_lock = REPO_ROOT / "requirements" / "dev.lock"

    print("Running pip dependency resolution for requirements/base.txt...")
    new_base_content = resolve_lockfile_with_pip(base_txt, BASE_LOCK_HEADER)

    print("Running pip dependency resolution for requirements/dev.txt...")
    new_dev_content = resolve_lockfile_with_pip(dev_txt, DEV_LOCK_HEADER)

    if check_mode:
        drift_detected = False
        if not base_lock.exists() or base_lock.read_text(encoding="utf-8") != new_base_content:
            print(
                f"ERROR: {base_lock} is out of sync with {base_txt}. "
                f"Run 'python scripts/regenerate_lockfiles.py' to update.",
                file=sys.stderr,
            )
            drift_detected = True

        if not dev_lock.exists() or dev_lock.read_text(encoding="utf-8") != new_dev_content:
            print(
                f"ERROR: {dev_lock} is out of sync with {dev_txt}. "
                f"Run 'python scripts/regenerate_lockfiles.py' to update.",
                file=sys.stderr,
            )
            drift_detected = True

        if drift_detected:
            return 1
        print("SUCCESS: Lockfiles are in sync with requirements files.")
        return 0

    # Write regenerated lockfiles to disk
    base_lock.write_text(new_base_content, encoding="utf-8")
    dev_lock.write_text(new_dev_content, encoding="utf-8")
    print(f"SUCCESS: Regenerated {base_lock} and {dev_lock} via pip dependency resolution.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
